### ISSUE TITLE
registerIdentifiedUser arguments conflict

### ISSUE THREAD

**Issue by GeertJohan** [deepak786/intercom_flutter#10]
I would like to suggest to only allow either userId or email for registerIdentifiedUser. Allowing both complicates usage and may result in undocumente behaviour as given userId and email might match different users. I had to look into kt code to see that giving email overrides the userId.

**Comment by GeertJohan** [comment]
Thanks for adding email by the way, its very useful.

**Comment by v3rm0n** [comment]
Ah thanks, I don't actually use this project anymore so haven't really tested any of this stuff out. Will keep this is mind for the next release.

**Comment by GeertJohan** [comment]
I could create a PR if you'd like?

**Comment by v3rm0n** [comment]
That would be awesome!
