### ISSUE TITLE
Present an Article Programmatically

### ISSUE THREAD

**Issue by leidig54** [deepak786/intercom_flutter#116]
Please can we have the above functionality? This is available in both the iOS and Android SDKs natively. 

https://developers.intercom.com/installing-intercom/docs/ios-configuration
https://developers.intercom.com/installing-intercom/docs/android-configuration

Many thanks

**Comment by Zazo032** [comment]
This should be easy to implement, since it seems to be only a call with the article id. Are article ids strings or numbers? Also, do you know if this is also available on the web sdk? Since a web implementation is being developed at #111

**Comment by leidig54** [comment]
Hi @Zazo032. 

I can't find anything in the documentation about programatically displaying articles on web. By the looks of this article it's only the mobile SDK's that support it. https://www.intercom.com/help/en/articles/4615533-launch-articles-from-a-button-in-your-mobile-app

The article ID's are strings.
