### ISSUE TITLE
User session not properly destroyed after calling "logout"

### ISSUE THREAD

**Issue by kristianeaw** [deepak786/intercom_flutter#118]
How do I make sure that a user session is properly ended when a user logs out? I am calling both `logout` and `registerUnidentifiedUser`, but when logging out (from our internal auth system) and back in to a new account (different user id and email), I still see the chat messages from the previous logged in account, so the session is not destroyed it seems. Does anyone have a fix for this, or is it a problem with the SDK as well? Or am I missing something else?

**Comment by FilledStacks** [comment]
Any update on this?

**Comment by deepak786** [comment]
to log out the user from Intercom, just use `Intercom.logout()`.

or If you can provide a reproducible example of the issue then it would be easy to check.

**Comment by deepak786** [comment]
@kristianeaw @FilledStacks 

I created a sample to replicate this issue https://github.com/deepak786/intercom_flutter_issue_118. 
This is working fine for me.

- add your Intercom keys to the sample.
- Run the app.
- Click "login". This will create an "anonymous user" in the Intercom.
- After login, you will see two buttons "Open messenger" and "logout".
- Click "Open messenger" and send some messages.
- Go back and click "Logout".
- Click "login" again. This will create a new "anonymous user" in the Intercom.
- Click "Open messenger". Here you will not see the messages from the previous user.
- So this is working fine.

any queries, please let me know.

**Comment by deepak786** [comment]
closing this based on the above example.
