### ISSUE TITLE
Register with UserId doesn't work

### ISSUE THREAD

**Issue by kev52** [deepak786/intercom_flutter#13]
I do this:

`final userId = utf8.encode('MY_ID');
final secret = utf8.encode('MY_SECRET');

 final hmacSha256 = Hmac(sha256, secret);
 final hash = hmacSha256.convert(userId);

 await Intercom.setUserHash('$hash');`
    
if I call: await Intercom.registerIdentifiedUser(); //Error provide userId or mail
if I call: await Intercom.registerIdentifiedUser(userID: 'MY_ID'); //Error mail can't be empty
if I call: await Intercom.registerIdentifiedUser(userID: 'MY_ID', email: 'MY_MAIL'); //Error can't use both

What is going wrong here?

**Comment by Spikes042** [comment]
I can't replicate this, more importantly:
`if I call: await Intercom.registerIdentifiedUser(userID: 'MY_ID'); //Error mail can't be empty`

PS: Verify that the generated hash is as expected here: https://app.intercom.com/a/apps/{intercom_app_id}/settings/identity-verification/android
