### ISSUE TITLE
Unlist deprecated package

### ISSUE THREAD

**Issue by Zazo032** [deepak786/intercom_flutter#131]
@v3rm0n do you still have access on pub.dev to Admin section on `intercom` plugin? If so, or you can somehow get access again, it could be great to discontinue and unlist that plugin:

![image](https://user-images.githubusercontent.com/2807712/110643016-ea011280-81b3-11eb-9f76-2ee10f1907d8.png)

Latest issue on its repository is from February 2021, so it could be great if it could be unlisted to avoid confusion.

**Comment by v3rm0n** [comment]
Sorry, I don't have access to that account anymore...

**Comment by Zazo032** [comment]
It's okay, lets leave it like that then. Maybe there's some option to directly contact pub.dev team to do that.
