### ISSUE TITLE
[iOS] Can't register only with email

### ISSUE THREAD

**Issue by marcuslma** [deepak786/intercom_flutter#14]
Hello, I am getting the following error when trying to register with email on iOS

`Runner[28519:158401] [Intercom] ERROR - 'userId' parameter must be an NSString and can't be nil or empty`

**Comment by Spikes042** [comment]
Duplicate of #13

**Comment by Spikes042** [comment]
#
Duplicate of #13

**Comment by zanuka** [comment]
Having the same issue @marcuslma ... works fine on Android, going to test #15 on my fork...

**Comment by v3rm0n** [comment]
Fixed in `2.0.2`
