### ISSUE TITLE
Question: Are mobile carousels supported?

### ISSUE THREAD

**Issue by saarikivit** [deepak786/intercom_flutter#140]
Hey, I wanted to ask you, weather mobile carousels are supported?
Thanks!

**Comment by Zazo032** [comment]
Are mobile carousels dependant on an Intercom SDK version? Or a native method call?

**Comment by deepak786** [comment]
https://developers.intercom.com/installing-intercom/docs/android-configuration#section-present-a-carousel-programmatically
