### ISSUE TITLE
How to use `sendTokenToIntercom` properly?

### ISSUE THREAD

**Issue by volodymyr-mitso** [deepak786/intercom_flutter#149]
Hi. I'm trying to send iOS device token to Intercom. I was doing this:
``` 
final token = await FirebaseMessaging.instance.getAPNSToken();
await Intercom.sendTokenToIntercom(token);
```
After some testing I realised it is not working. Push notification can't be received.

After adding this lines in `AppDelegate.m` in my app it worked and notifications were shown:
```
- (void)application:(UIApplication *)app didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    NSString *str = [NSString stringWithFormat:@"Device token: %@", deviceToken];
    NSLog(@"%@", str);
    [Intercom setDeviceToken:deviceToken];
}
```
But this approach will not work with my Authentication. I want to send device token only if user is authorised but not every time when app launched.

I made platform channel and then realised that it almost the same code you are using in `sendTokenToIntercom` method:
```
final token = await FirebaseMessaging.instance.getAPNSToken();
await IntercomPlatformChannel.sendDeviceTokenToIntercom(token);
```
```
NSString *stringToken = call.arguments[@"deviceToken"];
NSLog(@"%@", stringToken);
NSData *dataToken=[stringToken dataUsingEncoding:NSUTF8StringEncoding];
NSLog(@"%@", dataToken);
[Intercom setDeviceToken:dataToken];
result(@"success");
```
I'm not familiar with Objective-C, I just found everything needed online.

String token from method `getAPNSToken` is similar to  NSData `deviceToken` from `didRegisterForRemoteNotificationsWithDeviceToken` method, but they are different from NSData `dataToken` from my method, for example:
- String `token`: 6FC985B48B7CDF6CE9DDA988446B4111C8577BB00C7A5C13F3F71A3C1D453453
- NSData `deviceToken`: <6fc985b4 8b7cdf6c e9dda988 446b4111 c8577bb0 0c7a5c13 f3f71a3c 1d453453>
- NSData `dataToken`:  <36464339 38354234 38423743 44463643 45394444 41393838 34343642 34313131 43383537 37424230 30433741 35433133 46334637 31413343 31443435 33343533>

What am I doing wrong? In Firebase library NSData is converted to NSString. Basically NSData is converted to String and back, but result is not the same as original and push notifications don't work.

**Comment by obrunsmann** [comment]
Having the same issue here... anyone with a solution?

**Comment by deepak786** [comment]
Use 
```
final token = await FirebaseMessaging.instance.getToken();
await Intercom.sendTokenToIntercom(token);
```

**Comment by obrunsmann** [comment]
@deepak786 have you tried this and it worked? Because with this call you only get the Firebase Messaging token not the APNS token.
The intercom SDK expects an APNS token and has no firebase messaging integration for iOS (https://developers.intercom.com/installing-intercom/docs/ios-push-notifications)

**Comment by deepak786** [comment]
I will test that.

**Comment by deepak786** [comment]
According to the documentation, https://developers.intercom.com/installing-intercom/docs/ios-push-notifications#section-step-3-register-device-tokens, It seems that we need to pass the APNS token to Intercom for iOS but without encoding.

But in the code https://github.com/v3rm0n/intercom_flutter/blob/359663fb2e49103b501328a3a8c1bcd6a1adca02/intercom_flutter/ios/Classes/IntercomFlutterPlugin.m#L125
We are encoding the token and then sending that token to Intercom.

@obrunsmann could you please test the push notifications by commenting the above code from the method channel?

@Zazo032 do you have any idea?

**Comment by obrunsmann** [comment]
@deepak786 We tried that without encoding (crashed 😅 ) and with _dataUsingEncoding:NSASCIIStringEncoding_ which not worked at all again.

I verified that the APNS Token we receive via Firebase Messaging SDK was working and I was fully able to send messages via Apple APNS Api.
So something here is not working. Either the correct sending to intercom or there is an issue with messages delivery from intercom's side.

**Comment by Zazo032** [comment]
> @Zazo032 do you have any idea?

I haven't used the notifications feature of the plugin so I can't really say anything here

**Comment by volodymyr-mitso** [comment]
Hi @obrunsmann. Here is working solution.

When you want to send token:
```
      if (Platform.isAndroid) {
        final token = await FirebaseMessaging.instance.getToken();
        await Intercom.sendTokenToIntercom(token);
      } else if (Platform.isIOS) {
        final token = await FirebaseMessaging.instance.getAPNSToken();
        await IntercomPlatformChannel.sendDeviceTokenToIntercom(token);
      }
```

Method channel code:
```
import 'package:flutter/services.dart';
import 'package:your-app/utils/print_util.dart';

class IntercomPlatformChannel {
  static const MethodChannel platform = MethodChannel('your-app.com/intercom');

  static Future<void> sendDeviceTokenToIntercom(String deviceToken) async {
    try {
      PrintUtil.printLog('sendDeviceTokenToIntercom, start');
      if (deviceToken == null || deviceToken.isEmpty) {
        PrintUtil.printLog('sendDeviceTokenToIntercom, token is null or empty');
        return;
      }
      final result = await platform.invokeMethod(
        'sendDeviceTokenToIntercom',
        {'deviceToken': deviceToken},
      );
      PrintUtil.printLog('sendDeviceTokenToIntercom, result: $result');
    } catch (e, st) {
      PrintUtil.printLog('sendDeviceTokenToIntercom, error');
      PrintUtil.printError(e, st);
    }
  }
}
```

iOS main file code, `AppDelegate.m`:
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import Firebase;
#import <Intercom/Intercom.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;
    FlutterMethodChannel* yourAppIntercomChannel = [FlutterMethodChannel
                                                methodChannelWithName:@"your-app.com/intercom"
                                                binaryMessenger:controller.binaryMessenger];
    [yourAppIntercomChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
        if ([@"sendDeviceTokenToIntercom" isEqualToString:call.method]) {
            @try {
                NSString *deviceToken = call.arguments[@"deviceToken"];
                NSLog(@"%@", deviceToken);
                NSData *encodedToken=[self createDataWithHexString:deviceToken];
                NSLog(@"%@", encodedToken);
                [Intercom setDeviceToken:encodedToken];
                result(@"success");
            }
            @catch (NSException *exception) {
                result([FlutterError errorWithCode:@"error"
                                     message: exception.reason
                                     details:nil]);
            }
        } else {
          result(FlutterMethodNotImplemented);
        }
    }];

  [GeneratedPluginRegistrant registerWithRegistry:self];
   if (@available(iOS 10.0, *)) {
     [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
   }
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (void)application:(UIApplication *)app didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    NSString *str = [NSString stringWithFormat:@"Device token, result: %@",deviceToken];
    NSLog(@"%@", str);
    // Intercom push notification work with line below enabled.
    // But we don't want to send push token on every app launch.
    // We want to do it only if we are sure that user is authorised.
    // That's why platform channel is implemented above.
    // [Intercom setDeviceToken:encodedToken];
}

- (void)application:(UIApplication *)app didFailToRegisterForRemoteNotificationsWithError:(NSError *)err {
    NSString *str = [NSString stringWithFormat: @"Device token, error: %@", err];
    NSLog(@"%@", str);
}

- (NSData *) createDataWithHexString:(NSString*)inputString {
    NSUInteger inLength = [inputString length];
      
    unichar *inCharacters = alloca(sizeof(unichar) * inLength);
    [inputString getCharacters:inCharacters range:NSMakeRange(0, inLength)];
    
    UInt8 *outBytes = malloc(sizeof(UInt8) * ((inLength / 2) + 1));
    
    NSInteger i, o = 0;
    UInt8 outByte = 0;

    for (i = 0; i < inLength; i++) {
        UInt8 c = inCharacters[i];
        SInt8 value = -1;
        
        if      (c >= '0' && c <= '9') value =      (c - '0');
        else if (c >= 'A' && c <= 'F') value = 10 + (c - 'A');
        else if (c >= 'a' && c <= 'f') value = 10 + (c - 'a');
        
        if (value >= 0) {
            if (i % 2 == 1) {
                outBytes[o++] = (outByte << 4) | value;
                outByte = 0;
            } else {
                outByte = value;
            }
            
        } else {
            if (o != 0) break;
        }
    }
    
    NSData *a = [[NSData alloc] initWithBytesNoCopy:outBytes length:o freeWhenDone:YES];
    return a;
}

@end

```

Your iOS file code can be different but them main point is you need to use method channel and custom method for converting `NSString` to `NSData`.

**Comment by deepak786** [comment]
@VladimirMitso So basically we need to send the APNS token to Intercom by encoding like below.
```
NSData *encodedToken=[self createDataWithHexString:deviceToken];
```

correct?

**Comment by deepak786** [comment]
@obrunsmann @VladimirMitso could you please try this patch of intercom_flutter by overriding the library in pubspec.yml under `dependency_overrides:`
```
intercom_flutter:
    git:
      url: https://github.com/deepak786/intercom_flutter
      path: intercom_flutter
      ref: ios_send_token_patch
```

Please let me know if that works and then we will proceed to merge the adjustment.

**Comment by deepak786** [comment]
I tested the patch.
If the token from Firebase messaging is `6FC985B48B7CDF6CE9DDA988446B4111C8577BB00C7A5C13F3F71A3C1D453453`

Then the NSData token is `{length = 32, bytes = 0x6fc985b4 8b7cdf6c e9dda988 446b4111 ... f3f71a3c 1d453453 }`
This is What it prints on the console on the Flutter side.

I think it is working fine.

But I'm not able to test the notifications because I don't have a real iOS device. So I need feedback from you guys.

**Comment by volodymyr-mitso** [comment]
Hi @deepak786. Checked this PR https://github.com/v3rm0n/intercom_flutter/pull/150/files. It seems to me code is correct. But I don't have ability to test it now.

**Comment by obrunsmann** [comment]
Thank you so much for your work here. I can Test this of course. I try this weekend and give feedback to you asap.

**Comment by obrunsmann** [comment]
> @obrunsmann @VladimirMitso could you please try this patch of intercom_flutter by overriding the library in pubspec.yml under `dependency_overrides:`
> 
> ```
> intercom_flutter:
>     git:
>       url: https://github.com/deepak786/intercom_flutter
>       path: intercom_flutter
>       ref: ios_send_token_patch
> ```
> 
> Please let me know if that works and then we will proceed to merge the adjustment.

Uuuuuh yeeeah - that worked 
![Dance](https://media.tenor.com/images/bc706b8afb62b8714ad49b1bb407a614/tenor.gif)

I appreciate your work so much! Thank you!

**Comment by deepak786** [comment]
@obrunsmann @VladimirMitso 
The PR https://github.com/v3rm0n/intercom_flutter/pull/150 is merged into master.

---------------------------------
Writing the comment here in case someone else finds it difficult to use the method `sendTokenToIntercom`
1. The token must be an FCM token for Android.
2. The token must be an APNs token for iOS.

If you are using [`firebase_messaging`](https://pub.dev/packages/firebase_messaging) then
1. For Android  `String token = FirebaseMessaging.instance.getToken();`
2. For iOS get the token as `String token = FirebaseMessaging.instance.getAPNSToken();`

And pass this token to Intercom as `Intercom.sendTokenToIntercom(token);`

**_Note: the APNS token in the iOS simulator will be null. You need a real device._**

--------------------------------

Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid
