### ISSUE TITLE
Build warning for AndroidX

### ISSUE THREAD

**Issue by acoutts** [deepak786/intercom_flutter#156]
There is a benign build warning about some martially migrated code when running android builds:

```
Library '/root/.gradle/caches/modules-2/files-2.1/io.intercom.android/intercom-sdk-base/8.2.0/3ffe7671e92eff58e64d8e1ab79604f92889e731/intercom-sdk-base-8.2.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
```

**Comment by Zazo032** [comment]
What version of the plugin are you using?

**Comment by acoutts** [comment]
Doh! Forgot to include that.

```
intercom_flutter: ^3.1.0
```

**Comment by Zazo032** [comment]
Can you check if the same log appears on the latest `5.0.0`?

**Comment by acoutts** [comment]
I've just tested 5.0.0 and there is a different warning there (but the original one I reported is gone now). The way to make it happen is make sure your `$HOME/.gradle/caches` folder is empty / deleted, then do an android build. It won't show the warning on subsequent builds, only when the gradle cache is empty.

```
Note: /Users/andrewcoutts/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-5.0.0/android/src/main/java/io/maido/intercom/PushInterceptService.java uses unchecked or unsafe operations.
```

My project is using kotlin `1.4.32` and gradle `4.1.3`

**Comment by deepak786** [comment]
Intercom Android SDK is updated in `intercom_flutter: 5.0.0`. Currently, the SDK version 10.0.0 is being used.

> Note: /Users/andrewcoutts/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-5.0.0/android/src/main/java/io/maido/intercom/PushInterceptService.java uses unchecked or unsafe operations.


@acoutts you can ignore the above warning.

closing this as intercom_flutter: 5.0.0 resolved your issue. Feel free to create a new one, if you still have the issue.

**Comment by Zazo032** [comment]
Versión `5.0.0` has a different warning, maybe this should be kept open and change the description, or add that to a separate issue

**Comment by deepak786** [comment]
will be resolved in https://github.com/v3rm0n/intercom_flutter/pull/159
