### ISSUE TITLE
Android resource linking failed - unexpected element <queries> found in <manifest>

### ISSUE THREAD

**Issue by misaelriojasftf** [deepak786/intercom_flutter#158]
So It was time to update the packages from the project. I was using 2.2.0 & by upgrading to 5.0.0 I got the following error

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/m-004/.gradle/caches/transforms-2/files-2.1/cee4dc604d7d8065780025d790e856bb/jetified-intercom-sdk-base-10.0.0/AndroidManifest.xml:9:5-17:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

doing flutter doctor

```
➤ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)
```

**Comment by misaelriojasftf** [comment]
So after hours of research, I've could "solve" this. my android app is quite old. <queries> tag looks that are for android 11 and an update for the version was required.

so I created a new flutter application and checked the versions it was using it and move the following files

>/android/build.gradle
![image](https://user-images.githubusercontent.com/48217522/127718630-01310c8f-9b88-433e-93c6-d1ca58c39f57.png)

>/android/gradle/wrapper/gradle-wrapper.properties
![image](https://user-images.githubusercontent.com/48217522/127718739-1d5e82b5-5aab-4a6a-94d8-97a34a3fe9b1.png)

>/android/app/build.gradle
![image](https://user-images.githubusercontent.com/48217522/127718827-f1273fdb-f45c-43c0-9d18-8dd2c1c85dbb.png)

so just after that, I could run the app again. not sure if this is the real fix but if this could help someone else that's great.

**Comment by deepak786** [comment]
`queries` element is added in Android 30 (API 11).
Intercom's latest SDK versions use the queries element for some Intents as required.

And `intercom_flutter: 5.0.0` uses the latest Intercom Android SDK version.

So you need to use minimum Android Gradle plugin version 3.5.4 (it supports queries element) under `/android/build.gradle` and the compatible Gradle version in `gradle-wrapper.properties`.
```
classpath 'com.android.tools.build:gradle:3.5.4'
```

I think this is enough.
Rest things depend on your project like compile and target SDK version etc.
