### ISSUE TITLE
Pub.dev is showing <br/> tag on the Readme

### ISSUE THREAD

**Issue by Raunakk02** [deepak786/intercom_flutter#160]
Thanks for this amazing package!
There's something that I noticed while browsing the Readme.
As we can see in the attached screenshot, the `<br/>` tag is visible in the line just above the `Usage` header on the Readme section of the pub.dev.

![br_tag](https://user-images.githubusercontent.com/56073198/128503274-c553af2f-7344-46bf-8985-097237683e3a.PNG)

**I would love to create a fix for this issue! So, I request you to please provide me the opportunity.**

**Comment by Zazo032** [comment]
Thanks for noticing, feel free to open a PR to fix it 😀

**Comment by Raunakk02** [comment]
Thanks, @Zazo032!

**Comment by Raunakk02** [comment]
@Zazo032 can you please review the PR #161?
