### ISSUE TITLE
Steps to get Intercom working after installation?

### ISSUE THREAD

**Issue by ashleyabrooks** [deepak786/intercom_flutter#164]
Hi! I went through the steps in the README and installed the library, but I'm seeing "Something went wrong" when displaying the Intercom messenger. Reading through some other issues, I think I need to register the user.

Is that the only step? Wondering if there's more documentation for all the steps needed after installation.

**Comment by ningo-agilityio** [comment]
Hi @ashleyabrooks is your issue solved yet?

**Comment by simplenotezy** [comment]
I have the same issue - the documentation does not seem to explain how to register af user.

I followed all steps and I see this screen:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/3786627/192300938-f4ec7910-23ef-4a0f-852d-3efc15432189.png">

@ashleyabrooks would be nice if you shared what made it work for you.

**Comment by Zazo032** [comment]
https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/README.md?plain=1#L39

You have to call any of this methods, depending on your requirements:

- [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html)
- [loginUnidentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginUnidentifiedUser.html)
