### ISSUE TITLE
Change incoming message notification behavior.

### ISSUE THREAD

**Issue by rodrigonepomuceno** [deepak786/intercom_flutter#165]
Hello....

Is there a possibility of not showing the popup when receiving a new message?
Instead of receiving this message I intercept this, and put an incoming message counter to customize in an area of ​​the app with a message counter in an icon.

I couldn't do that. If you have this possibility, can anyone help me with any tips?

**Comment by deepak786** [comment]
@rodrigonepomuceno 

to hide the incoming message popups in your app, you need to use
```
Intercom.setInAppMessagesVisibility(IntercomVisibility.gone);
```

You can display the unread message count anywhere. To get and listen for counts, you have to use
```
Intercom.getUnreadStream().listen((data) {
      print(data.toString()); // this will be the count of unread conversations
});
```

**Comment by rodrigonepomuceno** [comment]
Sorry I'm late. But it worked. Thank you very much for the feedback.

**Comment by emmett-deen** [comment]
Would love to have this for web

**Comment by deepak786** [comment]
@rodrigonepomuceno Glad to know that it worked.
Please don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid

@emmett-deen As per my knowledge, there is no equivalent method in Intercom JS.
