### ISSUE TITLE
Could not determine artifacts for io.intercom.android:intercom-sdk:10.0.0: Skipped due to earlier error

### ISSUE THREAD

**Issue by thanhbinh84** [deepak786/intercom_flutter#168]
After upgrade into Android Studio Arctic Fox, I cannot build android app with intercom any more: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileStagDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:stagDebugRuntimeClasspath'.
   > Could not determine artifacts for io.intercom.android:intercom-sdk:10.0.0: Skipped due to earlier error
```

Tried 
```
intercom_flutter: ^4.0.0
intercom_flutter: ^5.0.2
```

```
android.enableJetifier=true
android.useAndroidX=true
```

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`

**Comment by deepak786** [comment]
@thanhbinh84 

I tried to create a build of the example app with the latest android studio `Arctic Fox` and it worked fine. There is no issue.

![Screen Shot 2021-09-20 at 8 38 49 PM](https://user-images.githubusercontent.com/14223997/134026532-db48a18a-5fa5-444f-8733-2841edeaaba6.png)

please share the sample code that reproduces the mentioned issue.

**Comment by thanhbinh84** [comment]
@deepak786 
Could you share your flutter, JSE and grade version? Here are mine 

```
Flutter (Channel stable, 2.2.3, on macOS 11.4)
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
```

**Comment by Zazo032** [comment]
You should use Java 8 or 11

**Comment by thanhbinh84** [comment]
I cannot test now as I have to rollback previous AS to continue my works. It would be great if you can share your working environment so I can try later. Thanks

**Comment by deepak786** [comment]
```
Flutter (Channel stable, 2.5.0, on macOS 11.5.2)
Java(TM) SE Runtime Environment (build 9+181)
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
```

**Comment by deepak786** [comment]
try adding `compileOptions` with `sourceCompatibility` to JAVA 8 inside the `android/app/build.gradle`

```
android {

    compileSdkVersion...
    ...

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by thanhbinh84** [comment]
Thanks, I will try again when having a chance.
