### ISSUE TITLE
Testing becomes impossible

### ISSUE THREAD

**Issue by RafaRuiz** [deepak786/intercom_flutter#170]
When having all calls static, testing this is impossible.
Would it be good to create an aside "instance" that starts with an initialization then with that object, you can call anything else?

Example:
Instead of:
```
Intercom.initialize().then((_) => Intercom.displayMessenger());
```

I would do:

```
class Intercom ... 

Intercom._();

static Future<Intercom> initialize(...) { ... }

void displayMessenger() { }
// ... other methods
```

I can submit a PR for this.

**Comment by deepak786** [comment]
@RafaRuiz 
I don't think that this is necessary. Also, this would be a breaking change.

is there an issue using the static functions?

**Comment by RafaRuiz** [comment]
It would be a breaking change, but we can go step by step (deprecating).
If all the methods are static, we can't mock them with [`mockito`](https://pub.dev/packages/mockito) or [`mocktail`](https://pub.dev/packages/mocktail)

Imagine I want to mock that the initialization worked but `displayMessenger` didn't, for some reason. I can't do that with the current implementation

**Comment by deepak786** [comment]
@Zazo032 what do you think about this?

**Comment by Zazo032** [comment]
I like the instance approach, Firebase plugins did the same thing, and if it helps on the testing side, I think there are no downsides. However, we should do the addition, deprecation and removal in different releases

**Comment by deepak786** [comment]
We can't have both static and instance members with the same name https://github.com/dart-lang/language/issues/1711
So to implement the instance approach, we have to delete the static methods.
