### ISSUE TITLE
Bump SDK version

### ISSUE THREAD

**Issue by ampedersen** [deepak786/intercom_flutter#172]
Hi,

Would be awesome if you would bump the SDK version (Intercom SDK).

I think you are on 10.0.x or something - 10.2 would be fantastic.

Thanks

**Comment by deepak786** [comment]
new version `intercom_flutter: 5.1.0` is released which updates the native Intercom SDK version.

Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid :)
