### ISSUE TITLE
SDK for iOS and Android bump to 10.2.0 or higher please

### ISSUE THREAD

**Issue by michael-monta** [deepak786/intercom_flutter#176]
Hey!

In order for our company's Intercom bot to work correctly with iOS and Android users, we've been told the SDK version for iOS and Android with our Flutter Plugin needs to be higher than the current 10.0.0, and needs to be at least 10.2.0

Could you update this please?

**Comment by deepak786** [comment]
Will update the SDK version by this weekend.

**Comment by michael-monta** [comment]
Thanks Deepak786 - can you confirm if it has been updated yet? :)

**Comment by deepak786** [comment]
new version `intercom_flutter: 5.1.0` is released which updates the native Intercom SDK version.

Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid :)
