### ISSUE TITLE
Lead Creation

### ISSUE THREAD

**Issue by LijuDaniel** [deepak786/intercom_flutter#177]
Unable to create Lead with SDK. 
When i try to create a 'lead' or updating a 'role',  in dashboard its still showing as a user.

Passing 'role' & 'lead category' as custom attributes.

<img width="246" alt="Screenshot 2021-10-28 at 8 07 40 PM" src="https://user-images.githubusercontent.com/27279731/139278647-9ffa9742-1d07-49df-98ab-d399b6827d61.png">

**Comment by deepak786** [comment]
@LijuDaniel A lead is an unidentified person who started the conversation.
And that lead becomes a user if he/she login or signs up.

https://www.intercom.com/help/en/articles/310-how-do-visitors-leads-and-users-work-in-intercom

By providing the custom attributes, you can't create a lead. Custom attributes are additional data related to lead or user.

**Comment by deepak786** [comment]
check this article to register users and visitors
https://developers.intercom.com/installing-intercom/docs/android-installation#section-register-your-logged-in-and-visitors

To create a lead, your user must be a visitor.
