### ISSUE TITLE
Logging Events to Intercom

### ISSUE THREAD

**Issue by zjoh5253** [deepak786/intercom_flutter#185]
Hi there, I was looking for an Intercom.logEvent() function or something similar that would allow us to send an event to intercom based on specific user actions. Does this exist currently? If not, is there a workaround or something in a future release that would enable this behavior. Thanks!

**Comment by Zazo032** [comment]
https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/logEvent.html
