### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by angus-gow** [deepak786/intercom_flutter#193]
I'm trying to implement push notifications, but this doesn't appear to be working through intercom. I'm not seeing any error on the intercom side but the implementation via the plugin is not clear. Is it possible to be pointed in the direction of some documentation or steps than need to be followed to make this work?

**Comment by deepak786** [comment]
https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter#push-notifications-in-combination-with-fcm

**Comment by deepak786** [comment]
@angus-gow on which platform are you having problems with the push notifications?

**Comment by deepak786** [comment]
https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter#push-notifications-setup
