### ISSUE TITLE
Something went wrong on 5.3.0

### ISSUE THREAD

**Issue by abed-supy-io** [deepak786/intercom_flutter#201]
-  it happens i when try to open massenger or an displayHelpCenter

**Comment by deepak786** [comment]
@abednajjar27 Please explain the issue in detail.
also please try the example app and check are you having the same issue?

**Comment by abed-supy-io** [comment]
**[fixed]** 
=> You have to register your user for  intercom can work
like this **Intercom.registerIdentifiedUser(email: user.email)**;
or your intercom screen give you  this message "Something went wrong";
I think they have to  throw error when it  has not register user yet

**Comment by deepak786** [comment]
In the mobile app, you have to make sure that the user is registered already (identified or unidentified) with Intercom, then Intercom messenger, for e.g, works.

closing this.
