### ISSUE TITLE
Exit button on main screen after Intercom.displayMessenger() not going back

### ISSUE THREAD

**Issue by PieterPicup** [deepak786/intercom_flutter#203]
I am not sure what other info I can give on this one.

The exit X button at the top right of the main landing screen of the intercom messenger does not go back or close the messenger.
If I hit the back button of the device it closes as expected.

Am I missing some setup or is this an expected behavior?

All other functions of the lib seem to be working correctly.

**Comment by deepak786** [comment]
@PieterPicup have you tested the example app?

**Comment by PieterPicup** [comment]
@deepak786 I have tried it. It opens the messenger but it does not load even with my keys in place. And the X button does work.
I am still not sure why the X button will not work and close the messenger in my app.

**Comment by deepak786** [comment]
@PieterPicup Messenger will load the messages only if you have already registered the user in Intercom, either identified or unidentified.

**Comment by PieterPicup** [comment]
@deepak786 Ah yes thank you forgot about that. Could you confirm what that button does in the lib? Nav.pop?
I am not getting any indication when I click the button as to what the flutter side if things is trying to do.
Only clicking the back button of device closes the messenger.

**Comment by deepak786** [comment]
@PieterPicup the x button on the messenger will just close the messenger. By the way, the code is not exposed by the Intercom.
intercom_flutter is just a wrapper to use the Intercom SDKs.

If you trying to close the messenger by yourself (your code), then try to use `Intercom.hideMessenger()` https://pub.dev/documentation/intercom_flutter_platform_interface/latest/intercom_flutter_platform_interface/IntercomFlutterPlatform/hideMessenger.html

**Comment by PieterPicup** [comment]
@deepak786 Thanks for the feedback.
I was hoping the wrapper had some kind of hook into that button click that might be malfunctioning in my app.
I will have to investigate at a later stage after alpha of my app.

**Comment by deepak786** [comment]
If you like the package, don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid

**Comment by deepak786** [comment]
@PieterPicup just checking which intercom_flutter version is not closing the messenger when clicking on close (x) icon?

**Comment by deepak786** [comment]
This issue was resolved in the [10.4.1 version](https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md#version-1041).
In the latest `intercom_flutter: 6.0.0` we are using the SDK version `10.6.1`. So please make sure you are using the updated SDK version.

If you still have an issue with the latest SDK, please let me know.

**Comment by PieterPicup** [comment]
> @PieterPicup just checking which intercom_flutter version is not closing the messenger when clicking on close (x) icon?

Unfortunately I cannot confirm which version I was using when I had the issue.

I did do a flutter upgrade just after we had this chat and the issue seemed to be resolved and I have ^5.1.0+1 in my pubspec.



> This issue was resolved in the [10.4.1 version](https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md#version-1041). In the latest `intercom_flutter: 6.0.0` we are using the SDK version `10.6.1`. So please make sure you are using the updated SDK version.

> 
> If you still have an issue with the latest SDK, please let me know.

Glad I was not just imagining things. Thanks for keeping us up to date and getting the issue sorted.
