### ISSUE TITLE
[question] Can I check if user is registered before launching messenger?

### ISSUE THREAD

**Issue by jsgalarraga** [deepak786/intercom_flutter#209]
If you execute the `displayMessenger` method without registering the user first, an error screen is shown.
Is there a way to check if the user is registered beforehand? 
So I can write something like:

```dart
if(Intercom.isUserRegistered()){
  Intercom.displayMessenger();
} else {
  await Intercom.registerUnidentifiedUser();
  Intercom.displayMessenger();
}
```

**Comment by deepak786** [comment]
@jsgalarraga There is no such API provided by the Intercom. But you can handle this by itself in your app. When you use the API `Intercom.registerUnidentifiedUser();`, save the status in shared preferences (e.g) from your app.

**Comment by jsgalarraga** [comment]
@deepak786 Thank you for your suggestion!
