### ISSUE TITLE
UI issue after change language from en to ar 

### ISSUE THREAD

**Issue by binSaed** [deepak786/intercom_flutter#213]
### Stepes

> display messenger with en language 
> close messenger 
> display messenger with ar language 

![0c6246fb-2505-4095-8a16-63b9b366cd5c](https://user-images.githubusercontent.com/33700292/155879390-8ce4fcef-e047-411c-bd53-93c7fa43635f.jpg)

**Comment by deepak786** [comment]
@AbdOoSaed how are you changing the app language? Please share the code sample.

**Comment by binSaed** [comment]
https://user-images.githubusercontent.com/33700292/156007884-4c7df7a6-3381-44c5-a0c7-80778ec5bda9.mp4

**Comment by binSaed** [comment]
```dart

    await Intercom.registerIdentifiedUser(userId: userId);
    await Intercom.updateUser(
      userId: userId,
      name: name,
      email: email,
      phone: phone,
      language: language,
    );
    await Intercom.displayMessenger();
```

**Comment by deepak786** [comment]
@AbdOoSaed I have submitted the issue to Intercom support. We have to wait for their feedback. You can also report it to them.

Meanwhile could you please check if it happens only on ios or on Android also?
Which intercom_flutter version you are using?

**Comment by binSaed** [comment]
This version i use
`  intercom_flutter: ^6.0.0`
and it happens only on ios

**Comment by deepak786** [comment]
@AbdOoSaed this is the reply from Intercom support:

> Hey Deepak 👋
> 
> Got a response from our engineers: Right to Left language isn't something that they official support on the mobile SDK's. Some things work and some don't so it's likely that small UI bugs will occurr. They do have plans to have full support in future, but there's nothing concrete there in terms of timeline for now.

So this is expected. To confirm this you can try to change to another language such as "pt" and see if you have the same issue.

**Comment by binSaed** [comment]
@deepak786 

https://github.com/intercom/intercom-ios/releases/tag/11.1.1

**Added support for RTL languages while searching for Articles on the Homescreen.**

may be update ios package will help

**Comment by deepak786** [comment]
Please test this override of intercom_flutter. This uses the iOS SDK version [11.2.0](https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md)

```
dependency_overrides:
  intercom_flutter:
    git:
      url: https://github.com/Shatha-Naami/intercom_flutter
      ref: upgrade-ios-intercom-sdk
      path: intercom_flutter
```

**Comment by deepak786** [comment]
new version `intercom_flutter: 6.1.0` is released which used latest Intercom iOS version 11.2.0. You can use that.

**Comment by deepak786** [comment]
`intercom_flutter: 6.2.0` is released as well that supports SDK v12. So you can try that.

**Comment by deepak786** [comment]
closing this based on https://github.com/v3rm0n/intercom_flutter/issues/213#issuecomment-1055856451

**Comment by binSaed** [comment]
Same issue with version 6.2
