### ISSUE TITLE
update to iOS/Android 12.0 SDKs

### ISSUE THREAD

**Issue by jamesdixon** [deepak786/intercom_flutter#219]
Intercom just had a massive release and has updated their iOS and Android SDKs to version 12 to support features such as Surveys.

I'd be happy to help update this if someone could explain the process :)

**Comment by Zazo032** [comment]
You can have a look at #218

**Comment by deepak786** [comment]
SDK v12 is released recently. I will do it this weekend.

**Comment by jamesdixon** [comment]
@deepak786 thanks! I actually just started following your example for the other SDK, so maybe you could take a quick peek when I submit the PR? It doesn't look like the SDKs have any breaking changes.

**Comment by jamesdixon** [comment]
PR here: https://github.com/v3rm0n/intercom_flutter/pull/220

**Comment by deepak786** [comment]
version `intercom_flutter: 6.2.0` is released.

Don't hesitate to buy me a coffee :)
https://www.buymeacoffee.com/deepakdroid

**Comment by jamesdixon** [comment]
Thanks! Coffee sent 🙏
