### ISSUE TITLE
Header text color is not inverted on dark background (brand color) and not readable.

### ISSUE THREAD

**Issue by mtskf** [deepak786/intercom_flutter#222]
Web version
<img width="219" alt="image" src="https://user-images.githubusercontent.com/315819/160531203-84abbf6b-5f94-43d2-b9d7-4ab57144de63.png">

Mobile app version
<img width="228" alt="image" src="https://user-images.githubusercontent.com/315819/160531430-49c03afa-518a-49a6-a8ab-e11f49e7e2c6.png">

**Comment by deepak786** [comment]
@mtskf which interom_flutter you are using?
Seems to be an issue with SDK itself. Could you please report the same to Intercom support?

**Comment by mtskf** [comment]
Thanks, @deepak786
I use the latest version -> intercom_flutter: ^6.2.0
Not sure where to report...

**Comment by deepak786** [comment]
Go to your Intercom account dashboard. Click on the icon displayed at the bottom right corner of the page.

**Comment by deepak786** [comment]
@mtskf I also contacted Intercom Support and below is their reply.

![Screen Shot 2022-04-01 at 11 11 13 PM](https://user-images.githubusercontent.com/14223997/161314730-eaf9e5aa-3158-4c2d-bf32-e96aad0f4810.png)
