### ISSUE TITLE
Api call failed: Error.list

### ISSUE THREAD

**Issue by SteveOye** [deepak786/intercom_flutter#223]
Api call failed: {"type":"error.list","request_id":"request_id","errors":[{"code":"not_found","message":"Resource Not Found"}]}

**Comment by deepak786** [comment]
@SteveOye What exactly you were doing when you have this issue?
Could you please share the repro?

**Comment by SteveOye** [comment]
await Intercom.displayMessenger();

Called  displayMessage

**Comment by deepak786** [comment]
could you please report this to Intercom support? It seems that there is some issue with your Intercom account.

**Comment by deepak786** [comment]
@SteveOye which intercom_flutter version you are using?

**Comment by SteveOye** [comment]
Version 6.2.0

**Comment by SteveOye** [comment]
Just switched down to version 6.0.0 and it works fine now. So, I think there's an issue with 6.2.0 @deepak786

**Comment by deepak786** [comment]
`intercom_flutter: 6.2.0` uses SDK v12 (12.0.0) for both Android and iOS.
`intercom_flutter: 6.0.0` uses Android SDK version 10.6.1 and iOS SDK version 11.0.1

**Comment by deepak786** [comment]
I just tested the version `intercom_flutter: 6.2.0` and it is working fine for me.

you can try the example app and see if it works fine.

**Comment by SteveOye** [comment]
Okay, Will try it

**Comment by deepak786** [comment]
I already contacted Intercom Support and below is their reply.
![Screen Shot 2022-04-01 at 11 12 56 PM](https://user-images.githubusercontent.com/14223997/161314964-d1b1c39f-9588-47ee-a93c-0fd0236eeb1f.png)
