### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path

### ISSUE THREAD

**Issue by dokumanx** [deepak786/intercom_flutter#228]
`Intercom.instance.isIntercomPush` causes app crash with below stack trace:

```
W/cadoo.cadoo_de(18021): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/cadoo.cadoo_de(18021): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/cadoo.cadoo_de(18021): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/cadoo.cadoo_de(18021): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
D/AndroidRuntime(18021): Shutting down VM
E/AndroidRuntime(18021): FATAL EXCEPTION: main
E/AndroidRuntime(18021): Process: io.cadoo.cadoo_dev, PID: 18021
E/AndroidRuntime(18021): java.lang.RuntimeException: Unable to create service io.maido.intercom.PushInterceptService: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/lib/arm64, /data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(18021): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
E/AndroidRuntime(18021): 	at android.app.ActivityThread.access$1700(ActivityThread.java:247)
E/AndroidRuntime(18021): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
E/AndroidRuntime(18021): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18021): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18021): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18021): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(18021): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18021): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18021): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(18021): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/lib/arm64, /data/app/~~XwXixaHN1MhUPROLyP26UQ==/io.cadoo.cadoo_dev-86TuZMwnbyRVRyAwdM5lVg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(18021): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(18021): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(18021): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(18021): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(18021): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(18021): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4469)
E/AndroidRuntime(18021): 	... 9 more

```

**Comment by deepak786** [comment]
In intercom_flutter: 6.0.0, service `io.maido.intercom.PushInterceptService` is removed. Now it is not required
https://pub.dev/packages/intercom_flutter/changelog#600

**Comment by deepak786** [comment]
from which version did you upgrade to 7.0.0?

**Comment by dokumanx** [comment]
I used to use 6.0.0. Then I have switched to 7.0.0. Still facing the same issue.

**Comment by deepak786** [comment]
could you please provide the repro?

**Comment by deepak786** [comment]
or please run the example app and try to do what you are doing in your app. And see if you have the same issue?

**Comment by dokumanx** [comment]
It is a private repo. I run the example project. But It is not possible to reproduce my case. Since, example project only displays messenger. But the app crashes when I receive notifications.

**Comment by deepak786** [comment]
You can try the following.

- uninstall the app
- clean your build `flutter clean`
- run `flutter pub get`
- fresh install the app on your device.

**Comment by dokumanx** [comment]
It is still an issue. It causes app crashes to all android devices when they receive notifications.

**Comment by deepak786** [comment]
Do you have the same issue with 6.0.0 version?

**Comment by dokumanx** [comment]
Yes, I have. I switched to 7.0.0 and the issue still remains

**Comment by deepak786** [comment]
Do you still have this service `io.maido.intercom.PushInterceptService` in your manifest file?

**Comment by dokumanx** [comment]
Yes.

![image](https://user-images.githubusercontent.com/48089386/163685840-253bf863-f081-46fd-a8a3-5ee8ce03220a.png)

**Comment by deepak786** [comment]
So this is the Problem. Now, this service is not required.
Remove it from your manifest.
Read the changelog carefully https://pub.dev/packages/intercom_flutter/changelog#600

```
remove the service io.maido.intercom.PushInterceptService, if you have, from your AndroidManifest.xml.
```

**Comment by dokumanx** [comment]
I see. It also says that:

> remove the code to handle the background Intercom push from your firebase_messaging background handler. Now it is not required to handle manually.

I have the below handler for both FCM and Intercom notifications. Should I also remove Intercom.instance.handlePush()? Will it be handled automatically?

```dart
static Future<dynamic> showNotificationHandler(RemoteMessage message) async {
    final Map<String, dynamic>? data = message.data;

    if (data != null) {
      // Handle data message
      final dynamic data = message.data;
      if (await Intercom.instance.isIntercomPush(data)) {
        await Intercom.instance.handlePush(data);
        return;
      } else {
        if (message.notification != null) {
          showNotification(message);
        }
      }
    }

    if (message.notification != null) {
      showNotification(message);
    }
  }
```

**Comment by deepak786** [comment]
Yes, you can remove the code `await Intercom.instance.handlePush(data);` from this handler. Otherwise, you will see 2 notifications. One by your handler and one by the receiver `io.maido.intercom.PushInterceptReceiver`

**Comment by dokumanx** [comment]
So, I need to remove both handler and `await Intercom.instance.handlePush(data);` right?

**Comment by deepak786** [comment]
if you are not sending any notifications from Firebase manually then you can remove the handler.
But I think you are handling the other notifications with the code:
```
if (message.notification != null) {
      showNotification(message);
}
```

You can just comment the line `await Intercom.instance.handlePush(data);` in your handler.

**Comment by dokumanx** [comment]
I intended to handle both FCM and Intercom messaging. If intercom_flutter handles Intercom notifications internally, I believe that I need to remove `await Intercom.instance.handlePush(data);` part. My only concern is that removing the intercom handler leads to another issue when we receive Intercom notifications. I will try and let you know. Thank you for your help!

**Comment by deepak786** [comment]
Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid

**Comment by 1encore** [comment]
I am having this issue recently, surprisingly happens only on debug mode. Made all changes above

**Comment by 1encore** [comment]
@deepak786 can you please reopen the issue?
