### ISSUE TITLE
Is there a way to change Intercom notification icon?

### ISSUE THREAD

**Issue by dokumanx** [deepak786/intercom_flutter#229]
Receiving notifications with Intercom icon could lead to a problem. Since users will expect notifications with the app icon. Is there any way to change the app icon both on iOS and Android?

**Comment by deepak786** [comment]
@dokumanx you can add an icon named "intercom_push_icon.png" to each drawable folder.
check this https://developers.intercom.com/installing-intercom/docs/android-fcm-push-notifications#step-4-setting-your-fcm-icon-optional

on iOS, the notification icon is the icon from the asset `AppIcon.appiconset`.

**Comment by deepak786** [comment]
Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid

**Comment by dokumanx** [comment]
Can you be more specific about overriding drawable? I only found **res** under external libraries. And it doesn't seem to a proper way to override. 
![image](https://user-images.githubusercontent.com/48089386/163874008-707c8e3f-d911-40d1-bc58-85871a11b48f.png)

**Comment by deepak786** [comment]
You have to add the icon inside your app.
{PROJECT}/android/app/src/main/res/

If the drawable folders are not there then create them.
![Screen Shot 2022-04-19 at 2 14 17 AM](https://user-images.githubusercontent.com/14223997/163875012-73f6dc67-6ef7-42ab-8868-78008ea5517d.png)

**Comment by dokumanx** [comment]
Got it. Many thanks!
