### ISSUE TITLE
loginUnidentifiedUser not working on Android

### ISSUE THREAD

**Issue by ferrarafer** [deepak786/intercom_flutter#238]
The method `loginUnidentifiedUser` never returns from execution on Android platform.

**Comment by deepak786** [comment]
@ferrarafer could you please provide the sample about the issue?
You can modify the example app to provide the issue sample.

**Comment by ferrarafer** [comment]
Sorry, seems that if the user was logged in before, needs to logout from Intercom to login again. We fixed it that way on our app.

Thanks!

**Comment by atnpem** [comment]
I had the same issue, thx for the workaround.

**Comment by deepak786** [comment]
If the Intercom session already has a user then a new user will not be registered.
You can add `intercomStatusCallback` to check the error from Intercom.
