### ISSUE TITLE
CustomAttributes not being set

### ISSUE THREAD

**Issue by petekblaz** [deepak786/intercom_flutter#24]
I am trying to override language for intercom, depending on user  settings. 

Here I set language to portugal:
`customAttributes: {"languageOverride": "pt"}
`
but it is not being set in intercom. I can override all the other info (that is not part of customAttributes), but I cant override the language.

Any idea on how to change the language for some users?

**Comment by Zazo032** [comment]
As of https://github.com/intercom/intercom-java/issues/157, it seems that language can only be overridden on the initialize method, which is currently not supported. Try changing the variable name to `language_override` just in case they added support for this custom attribute later. If it doesn't work, we'll have to add a new parameter to the initialize method.

**Comment by petekblaz** [comment]
> As of [intercom/intercom-java#157](https://github.com/intercom/intercom-java/issues/157), it seems that language can only be overridden on the initialize method, which is currently not supported. Try changing the variable name to `language_override` just in case they added support for this custom attribute later. If it doesn't work, we'll have to add a new parameter to the initialize method.

I've tried language_override, language-override and languageOverride, and none seem to work.

Any idea on when this can be added?

**Comment by Zazo032** [comment]
Probably the initialize method will need a new parameter: https://www.intercom.com/help/configure-intercom/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages

**Comment by petekblaz** [comment]
> Probably the initialize method will need a new parameter: https://www.intercom.com/help/configure-intercom/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages

**Comment by Spikes042** [comment]
Looking through Intercom Android SDK, it doesn't allow passing through any other parameter except what's currently known.

```java
package io.intercom.android.sdk;

public abstract class Intercom {
    ...

    public static synchronized void initialize(android.app.Application application, java.lang.String apiKey, java.lang.String appId) { /* compiled code */ }
```

I believe that functionality is only available for the web/javascript SDK. So this can be closed now.

**Comment by Zazo032** [comment]
Thanks for the info @Spikes042, closing this because the plugin currently doesn't support the web implementation.

**Comment by deepak786** [comment]
we can now update the languageOverride as UserAttribute.
```
UserAttributes.Builder attributes = new UserAttributes.Builder();
attributes.withLanguageOverride("en");
```
