### ISSUE TITLE
Breaking changes for older versions with dependency versioning

### ISSUE THREAD

**Issue by igiazlas** [deepak786/intercom_flutter#243]
The versioning system of the main package follows the usual scheme of [major].[minor] with major introducing breaking changes and minor not. But the versioning of the dependencies `intercom_flutter_platform_interface` and `intercom_flutter_web` does not follow this convention which means that a blind flutter `pub upgrade` will upgrade them and break the functionality of older versions of the main package.

In particular, on my `pubspec.yaml`, I've locked the version of the package to `5.3.0`

```
intercom_flutter: ^5.3.0
```

because I need support for iOS <13. But when I run `flutter pub upgrade` the two dependencies are updated to their latest versions, `1.2.0` and `0.2.0` respectively. Those versions do not work with `5.3.0`. The issue that was triggered, but I suspect there are more, is 

```
MissingPluginException(No implementation found for method loginUnidentifiedUser on channel maido.io/intercom)
```

The temporary solution for my problem is to lock the versions of the requirements in my `pubspec.yaml`

```
intercom_flutter: ^5.3.0
intercom_flutter_platform_interface: 1.0.1
intercom_flutter_web : 0.0.4
```

The correct solution will be for the dependencies to also be bumped to new major versions when they introduce breaking changes for older versions of the main package.

**Comment by deepak786** [comment]
duplicate of https://github.com/v3rm0n/intercom_flutter/issues/236

@igiazlas We are already aware of this issue which occurred due to wrong versioning. We will take care of this in the future.
But for now, you need to override the dependencies:

```
dependency_overrides:
  intercom_flutter_platform_interface: 1.0.1
  intercom_flutter_web: 0.0.4
```
