### ISSUE TITLE
I Updated to the last version ( 7.2.0) and when received a notification from firebase the android app has crashed 

### ISSUE THREAD

**Issue by abed2-supy-io** [deepak786/intercom_flutter#244]
and i get this message:

E/AndroidRuntime(10271): java.lang.RuntimeException: Unable to instantiate service io.maido.intercom.PushInterceptService: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/base.apk"],nativeLibraryDirectories=[/data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/lib/arm64, /data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(10271): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3519)
E/AndroidRuntime(10271): 	at android.app.ActivityThread.access$1300(ActivityThread.java:199)
E/AndroidRuntime(10271): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
E/AndroidRuntime(10271): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10271): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(10271): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(10271): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10271): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(10271): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(10271): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/base.apk"],nativeLibraryDirectories=[/data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/lib/arm64, /data/app/io.supy.app-WPECFi8cuWnGOZe19C6iAA==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(10271): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(10271): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(10271): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(10271): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
E/AndroidRuntime(10271): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(10271): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3514)
E/AndroidRuntime(10271): 	... 8 more

**Comment by deepak786** [comment]
@abedulkader In the version [6.0.0](https://pub.dev/packages/intercom_flutter/changelog#600), the service `io.maido.intercom.PushInterceptService` is deleted.
So you have to remove this service from your manifest file.

You can check the similar issue https://github.com/v3rm0n/intercom_flutter/issues/228
