### ISSUE TITLE
MissingPluginException(No implementation found for method loginIdentifiedUserWithUserId on channel maido.io/intercom) on [ 5.3.0 version ] 

### ISSUE THREAD

**Issue by abed2-supy-io** [deepak786/intercom_flutter#245]
I am trying to send a user id and the user is not null able 
    with this method     Intercom.registerIdentifiedUser(userId: user.id);
    with 5.3.0 version 
    it stills getting this issue 
      #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
      <asynchronous suspension>
      #1      MethodChannelIntercomFlutter.loginIdentifiedUser (package:intercom_flutter_platform_interface/method_channel_intercom_flutter.dart:51:9)
      <asynchronous suspension>

**Comment by deepak786** [comment]
duplicate of https://github.com/v3rm0n/intercom_flutter/issues/236

@abedulkader this issue happened because of the wrong versioning.
As a workaround override the following dependencies in the pubspec.yaml as below:

```
dependency_overrides:
  intercom_flutter_platform_interface: 1.0.1
  intercom_flutter_web: 0.0.4
```

**Comment by abed2-supy-io** [comment]
@deepak786 
its happen also on 7.2.0 version 
so what should i put also ?

**Comment by deepak786** [comment]
There will be no issue with 7.1.0 and 7.2.0. 
if you using the older version then you need to override the dependencies otherwise not.

**Comment by abed2-supy-io** [comment]
@deepak786 
 i upgrade intercom_flutter: ^7.2.0
 and i replace the deprecated method with       Intercom.instance.loginIdentifiedUser(userId: user.id);

  i am stilling have this issue 
[log] MissingPluginException(No implementation found for method registerIdentifiedUserWithUserId on channel maido.io/intercom)
      #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
      <asynchronous suspension>
      #1      MethodChannelIntercomFlutter.loginIdentifiedUser (package:intercom_flutter_platform_interface/method_channel_intercom_flutter.dart:51:9)
      and this my pubsec.lock
      <asynchronous suspension
<img width="514" alt="Screen Shot 2022-05-17 at 3 35 54 PM" src="https://user-images.githubusercontent.com/105663043/168812331-0b6eb18a-4909-486d-88d1-3082ab601493.png">
>

**Comment by abed2-supy-io** [comment]
<img width="1515" alt="Screen Shot 2022-05-17 at 3 39 35 PM" src="https://user-images.githubusercontent.com/105663043/168812845-d2639c81-e8ca-4985-b629-e24535249517.png">

**Comment by deepak786** [comment]
Like I said then you need to remove the overridden dependencies.
Delete the below from your pubspec.yaml file:

```
dependency_overrides:
  intercom_flutter_platform_interface: 1.0.1
  intercom_flutter_web: 0.0.4
```
