### ISSUE TITLE
loginIdentifiedUser never executes with existing Intercom user session.

### ISSUE THREAD

**Issue by TejasShuklaWeserveCodes** [deepak786/intercom_flutter#246]
After we updated to intercom_flutter: ^7.2.0, our flutter build started to have this weird behavior at installation, the app crashed the 1st time after installation. With splash screen error.

Only  Intercom.instance.registerUnidentifiedUser(); work properly. Which creates a new user every time we use an app.
None of the methods below work for me.
Intercom.instance.updateUser(email:”testing@xyz.com”);
Intercom.instance.registerIdentifiedUser(email:”testing@xyz.com”);
Intercom.instance.loginIdentifiedUser(email:”testing@xyz.com”);

![Screenshot 2022-05-24 112310 (2)](https://user-images.githubusercontent.com/72876637/170007690-5f2eae95-6d11-4e29-9ea9-b8746de091a8.png)
![Screenshot 2022-05-24 112243 (2)](https://user-images.githubusercontent.com/72876637/170007695-aacccf04-d0cb-48a3-bd77-576e3a9de57e.png)
![Screenshot 2022-05-24 140905](https://user-images.githubusercontent.com/72876637/170007699-7a537de9-e0b3-4611-891a-870ed93ee7aa.png)
![Screenshot 2022-05-24 113942](https://user-images.githubusercontent.com/72876637/170007860-8f2ece8f-d1e9-418c-acf6-a761adcf5840.png)

**Comment by deepak786** [comment]
@TejasShukalPlutustec There is an issue with `loginUnidentifiedUser`. Please check https://github.com/v3rm0n/intercom_flutter/issues/242

But as per my testing, there is no issue with `loginIdentifedUser` and `updateUser`.

The above methods now have a `statusCallback` parameter. Could you please add that parameter and see if you get any error response.

```
Intercom.instance.loginIdentifiedUser(
      email:"testing@xyz.com",
      statusCallback: IntercomStatusCallback(
        onSuccess: () {
          print("Success");
        },
        onFailure: (error) {
          print(error.toString());
        },
      ),
    );
```

**Comment by TejasShuklaWeserveCodes** [comment]
If we use “intercom_flutter: 5.3.0” intercom version or lower then app work fine but intercom given an error for missing method “loginIdentifiedUserWithUserId”

If we use a higher version than app crash on installation time for the first time. If it's already installed then it works fine.
1st time on installation got below error msg.
W/FlutterActivityAndFragmentDelegate( 3436): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:61530/CiZ2ZjuyEkg=/

and in Firestore Crashlytics dashboard got below error msg.
Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/~~R3VJTwUYvT03vZlRxG_ySw==
/com.******-lK04a-LAp-rEtGr28Hnlbg==/base.apk"],nativeLibraryDirectories=[/data/app/~~R3VJTwUYvT03vZlRxG_ySw==/
com.******-lK04a-LAp-rEtGr28Hnlbg==/lib/arm64, /data/app/~~R3VJTwUYvT03vZlRxG_ySw==/com.******-lK04a-LAp-rEtGr28Hnlbg==
/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /vendor/lib64, /odm/lib64]]

**Comment by deepak786** [comment]
If you want to use the intercom_flutter version 5.3.0 or lower then override the following dependencies:

```
dependency_overrides:
  intercom_flutter_platform_interface: 1.0.1
  intercom_flutter_web: 0.0.4
```
See issue: https://github.com/v3rm0n/intercom_flutter/issues/236

=============================================================================

if you want to use the intercom_flutter version between >= 6.0.0 and < 7.1.0 then 
- you need to remove the service `io.maido.intercom.PushInterceptService` from your Manifest file if it is added see https://github.com/v3rm0n/intercom_flutter/issues/228
- Also override the above dependencies

=============================================================================

if you want to use the intercom_flutter >= 7.1.0 then
-  you need to remove the service `io.maido.intercom.PushInterceptService` from your Manifest file if it is added.

**Comment by TejasShuklaWeserveCodes** [comment]
I want to use intercom_flutter: 7.2.0 . Please give me a solution for latest version.
Just found some solution which says by removing below code from AndroidManifest it’ll work.
But it’s not working for me. Now I’m getting another error.

--<
service
     android:name="io.maido.intercom.PushInterceptService"
     android:enabled="true"
     android:exported="false">
     <
intent-filter
>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
     <
/intent-filter
>
 </service
>--

 Error:

Initialized Development App
E/FirebaseMessaging( 7661): Failed to get FIS auth token
E/FirebaseMessaging( 7661): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging( 7661): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.1:5)
E/FirebaseMessaging( 7661): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.1:8)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-messaging@@23.0.0:10)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.GmsRpc.startRpc(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.GmsRpc.getToken(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$9$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda5.start(Unknown Source:6)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-messaging@@23.0.0:6)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(com.google.firebase:firebase-messaging@@23.0.0:7)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$3$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 7661): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda10.run(Unknown Source:4)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseMessaging( 7661): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.6.0:2)
E/FirebaseMessaging( 7661): 	at java.lang.Thread.run(Thread.java:923)
E/FirebaseMessaging( 7661): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging( 7661): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:213)
E/FirebaseMessaging( 7661): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
E/FirebaseMessaging( 7661): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
E/FirebaseMessaging( 7661): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:377)
E/FirebaseMessaging( 7661): 	at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(Unknown Source:4)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseMessaging( 7661): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseMessaging( 7661): 	... 1 more

**Comment by deepak786** [comment]
which code you removed from AndroidManifest file?

**Comment by TejasShuklaWeserveCodes** [comment]
<
service
     android:name="io.maido.intercom.PushInterceptService"
     android:enabled="true"
     android:exported="false">
     <
intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
     </
intent-filter>
 </
service>

**Comment by deepak786** [comment]
on which device are you testing?
Does that device has play services?

**Comment by deepak786** [comment]
the above error is not related to intercom_flutter.
https://github.com/firebase/flutterfire/issues/3163
