### ISSUE TITLE
Error - Initializing app in both Android / iOS does not work and does not provide any error messages.

### ISSUE THREAD

**Issue by ghost** [deepak786/intercom_flutter#247]
The method Intercom.instance.initialize runs, but I can't seem to initialize the app. Inside the intercom settings for the workspace, I am given the following message: Intercom isn’t installed for your Android app yet, which makes me believe that the information I am providing isn't even reaching them, and if it is, I don't have access to any error that I could be happening. The method `Intercom.instance.initialize` is a Future<void> so no response is returned. The line runs just fine with my appId and api keys for both android and iOS but on the app, I get the following error (on the UI only)  when I attempt to execute `displayMessenger`:
Something went wrong.
![image](https://user-images.githubusercontent.com/47047124/174194848-c3b283dd-88d4-41f4-9fe3-5eae0392bd77.png)
No errors on the console, break points have been useless. I am using all the required sdk and target versions for the project as instructed in the documentation. I have tried using multiple different simulators with different os versions, as well as running on different environments and settings (release, debug, profile). Also tried running with different intercom workspaces, with no success.
Because this library isn't maintained by the intercom team, their support is very limited to this.

**Comment by Polemics** [comment]
Same issue here; I've also been searching for a work around by setting up through a WebView but no luck.

**Comment by deepak786** [comment]
Intercom messenger will work only if you have a user logged in to the Intercom either identified or unidentified.

**Comment by ghost** [comment]
I think what we are missing here is that step added to the documentation / example app. Both of them don't seem to mention this step, and for people just starting to use the library, meaning, that haven't implemented in other platforms before, it would be a long shot to find this out. @Polemics, the above recommendation works. you need to add either one of these lines:  `await Intercom.instance.loginIdentifiedUser(userId: 1234)`
or `await Intercom.instance.loginUnidentifiedUser();` before opening the messenger. This will do it.

**Comment by Polemics** [comment]
Yes this worked; thank you!

**Comment by deepak786** [comment]
Example app already mentions this.

![Screen Shot 2022-06-23 at 9 31 44 AM](https://user-images.githubusercontent.com/14223997/175206369-212d849b-fcbc-40af-bd79-4470cdcd10ed.png)
