### ISSUE TITLE
[Android] Notifications have strange behavior

### ISSUE THREAD

**Issue by sterallion** [deepak786/intercom_flutter#253]
I open the app, leave the app and tap the intercom notification.

**Expected results:** 
App opens.

**Actual results:** 
App opens and opens again like new.

https://user-images.githubusercontent.com/36900371/182690881-e4f29e63-2b9b-4e1f-93c1-7f8933abaddb.mp4

### Environment
Flutter 3.0.5
intercom_flutter 7.3.0

**Comment by deepak786** [comment]
Try giving "launchMode" attribute to your MainActivity in the Android manifest.

You can read about the launchMode here https://developer.android.com/guide/topics/manifest/activity-element#lmode

![Screen Shot 2022-08-04 at 1 50 24 AM](https://user-images.githubusercontent.com/14223997/182703060-bbf40834-8c62-4c79-9ac6-ac63fcc28883.png)

**Comment by sterallion** [comment]
@deepak786 Thank a lot for the information
