### ISSUE TITLE
Getting Error 

### ISSUE THREAD

**Issue by wtfup** [deepak786/intercom_flutter#254]
We are getting this while adding the package ![IMG-20220804-WA0022.jpg](https://user-images.githubusercontent.com/90644601/182850539-7cb9f6e3-04eb-4eb6-a40a-37f93aad8b18.jpg)

**Comment by Zazo032** [comment]
Did you initialize it with your api keys? https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter#usage

**Comment by Sanjaynavgurukul** [comment]
Yes I have initialised in main file with proper api keys.

**Comment by Zazo032** [comment]
> messenger will load the messages only if the user is registered in Intercom. either identified or unidentified.

Are you logging in a (un)identified user before displaying it?
- [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html)
- [loginUnidentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginUnidentifiedUser.html)

**Comment by deepak786** [comment]
It's necessary that the user must be logged in either identified or un-identified. Otherwise, the messenger will not load on the mobile app.

I will update the example app with comments.

**Comment by nbs-abdullah** [comment]
Hello, I'm facing the same issue. Every thing was working fine until I had to upgrade the plugin version from 2.2.0 to 5.3.0.
If I revert back to 2.2.0 it starts working but give the above error screen if I upgrade the plugin to anything above 3.0.0.
