### ISSUE TITLE
iOS messenger is being closed when app is foreground

### ISSUE THREAD

**Issue by fsayfitdinov** [deepak786/intercom_flutter#255]
iOS messenger is being closed when app is foreground. Expected behavior: messenger should not be closed if app is put on foreground and then resumed.

**Comment by deepak786** [comment]
@fsayfitdinov It's working fine for me. Could you please test with the example app?

**Comment by fsayfitdinov** [comment]
@deepak786 yes, you are right, the issue must be linked with my app not the package
