### ISSUE TITLE
Cannot zoom in and zoom out image attachment in message

### ISSUE THREAD

**Issue by RanaMusab** [deepak786/intercom_flutter#256]
In IOS we can zoom in/out image attachments but in android, I am unable to zoom in/out.

**Comment by Zazo032** [comment]
This could be an issue with Intercom's Android SDK

**Comment by RanaMusab** [comment]
Yes it should be fixed

**Comment by deepak786** [comment]
@RanaMusab could you please post the issue to the Intercom Support team?

**Comment by RanaMusab** [comment]
Ok sure

**Comment by deepak786** [comment]
@RanaMusab do you have any update from Intercom support?
Maybe you can try the latest version `intercom_flutter: 7.6.0` which uses the SDK v14.

**Comment by RanaMusab** [comment]
Yes i have talked with intercom support team they said this intercom
feauture is currently not available in for android devices they will add
this as soon as possible.

**Comment by deepak786** [comment]
@RanaMusab Thanks for the update.
Closing this based on your comment.

**Comment by RanaMusab** [comment]
Ok
