### ISSUE TITLE
Facing Theme issue please update android sdk to 12.4.3 

### ISSUE THREAD

**Issue by MusabAbid123** [deepak786/intercom_flutter#258]
i am getting black background on opening intercom in flutter app kindly update android SDK to latest version as they have solved this issue in the latest version.

[Please Check here change logs](https://github.com/intercom/intercom-android/releases/tag/12.4.3)

**Comment by NirpE** [comment]
Facing this same issue using intercom_flutter 7.4.1 on Android

Is there some workaround or specific theme you need to use for Flutter Android app? Black screen appears to be visible during the transitions of Intercom messenger.

@deepak786 are you seeing this yourself?

**Comment by deepak786** [comment]
@NirpE No, I haven't faced this issue.

**Comment by deepak786** [comment]
I tested `intercom_flutter: 7.4.1`. Before opening the Intercom messenger, a black screen is shown, and after that Intercom messenger slides up.

@NirpE Are you talking about the same issue?

**Comment by NirpE** [comment]
Yes exactly that. Black screen is shown while the bottom sheet opens/closes.
