### ISSUE TITLE
Register User not working

### ISSUE THREAD

**Issue by os20** [deepak786/intercom_flutter#26]
Hi,

I'm using the Pluig in my app.
Now I want to register an existing user using the method `Intercom.registerIdentifiedUser(userId: '2re54')`.

As result I get: Registerd User.

![1](https://user-images.githubusercontent.com/1292531/59600042-67434480-9100-11e9-9086-66cc6d3c1759.png)

But in the Intercom Dashbard the user data is not updated or displayed.

What is the error?

**Comment by Zazo032** [comment]
What version of the plugin are you using? I don't have a live Intercom key to test it right now but latest version was working fine in my app last time I checked

**Comment by os20** [comment]
Hello,

sorry for the late answer.
I am using version 2.0.3 of the dart plugin.

After I contacted Intercom about another matter, I was astonished to find out that the registration of users via the dart plugin was working.

So there is no need for action at the moment, because everything works as it should. :-)

Many greetings
