### ISSUE TITLE
Why is Intercom so big?

### ISSUE THREAD

**Issue by ChrisElliotUK** [deepak786/intercom_flutter#260]
After running `flutter build ios --analyze-size` I find that intercom.framework is 27mb. This seems way too big. Is it correct?
<img width="898" alt="Screenshot 2022-09-16 at 16 47 47" src="https://user-images.githubusercontent.com/102792401/190679112-8bc8eb14-782f-494a-8c0a-279fa97530d4.png">

**Comment by deepak786** [comment]
@ChrisElliotUK You need to ask the Intercom support team.

**Comment by deepak786** [comment]
@ChrisElliotUK do you have any update from Intercom support?
