### ISSUE TITLE
Set the height of messenger on mobile in flutter

### ISSUE THREAD

**Issue by keanyee** [deepak786/intercom_flutter#262]
Is it possible to set the height of the intercom messenger ? It automatically expands to the full mobile height.

I.e., How can I impose a size constraint on this function Intercom.instance.displayMessenger() ? 

Thanks.

**Comment by deepak786** [comment]
Not possible. There is no such parameter that we can pass to Intercom SDK.

**Comment by keanyee** [comment]
> Not possible. There is no such parameter that we can pass to Intercom SDK.

Thank you for your message.
