### ISSUE TITLE
minimum iOS target version required is 13.0 is too high

### ISSUE THREAD

**Issue by Elatech** [deepak786/intercom_flutter#271]
Can we make the SDK support iOS 11 at least? The SDK is so helpful and the current minimum SDK of iOS 13.0 leaves out a huge number of users from accessing intercom on our app. any help in this regard will be highly appreciated thanks.

**Comment by deepak786** [comment]
@Elatech iOS 13 is the minimum OS version supported the native Intercom SDK starting with v11.
You need to use the `intercom_flutter: 5.3.0`. It uses older SDK version that supports iOS 10.
