### ISSUE TITLE
[BUG] - Content could not be loaded

### ISSUE THREAD

**Issue by michaeljajou** [deepak786/intercom_flutter#274]
Following the tutorial mentioned in the Pubspec (pretty much just initializing intercom and displaying the messenger), this is the screen I am getting when trying to display the messenger:

- iOS 16.1
- iPhone 14 Pro Simulator

![Screenshot](https://user-images.githubusercontent.com/45440199/206601203-5598b59e-bd35-4449-97e1-2e7197a9b6d5.png)

**Comment by deepak786** [comment]
@michaeljajou Make sure there is an Intercom user before displaying the Messenger.
`Intercom.instance.loginIdentifiedUser()` or `Intercom.instance.loginUnIdentifiedUser()`.

![Screen Shot 2022-12-09 at 10 03 33 AM](https://user-images.githubusercontent.com/14223997/206624679-352026f2-9786-483a-9098-169e51e9bc9c.png)

**Comment by insysinfo** [comment]
> Following the tutorial mentioned in the Pubspec (pretty much just initializing intercom and displaying the messenger), this is the screen I am getting when trying to display the messenger:
> 
> * iOS 16.1
> * iPhone 14 Pro Simulator
> 
> ![Screenshot](https://user-images.githubusercontent.com/45440199/206601203-5598b59e-bd35-4449-97e1-2e7197a9b6d5.png)

i'm facing same issue Android and Ios both...

**Comment by deepak786** [comment]
I have tested the example app with the latest intercom_flutter.

```
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // TODO: make sure to add keys from your Intercom workspace.
  await Intercom.instance.initialize(
    'appId',
    androidApiKey: 'androidApiKey',
    iosApiKey: 'iosApiKey',
  );
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Intercom example app'),
        ),
        body: Center(
          child: TextButton(
            onPressed: () async {
              // NOTE:
              // Messenger will load the messages only if the user is registered
              // in Intercom.
              // Either identified or unidentified.
              // So make sure to login the user in Intercom first before opening
              // the intercom messenger.
              // Otherwise messenger will not load.
              await Intercom.instance.loginUnidentifiedUser();
              Intercom.instance.displayMessenger();
            },
            child: Text('Show messenger'),
          ),
        ),
      ),
    );
  }
}

```

And it is working fine. 
So closing this issue based on the testing. If you still face this issue, feel free to comment and provide a reproducible sample.
