### ISSUE TITLE
this issue face after latest version of intercom_flutter: ^7.6.1

### ISSUE THREAD

**Issue by insysinfo** [deepak786/intercom_flutter#275]
this issue face after latest version of intercom_flutter: ^7.6.1
![image](https://user-images.githubusercontent.com/70749329/206620297-35dcf80f-3e4b-4df6-9324-6b89c969bf87.png)

**Comment by deepak786** [comment]
@insysinfo Make sure there is an Intercom user before displaying the Messenger.
`Intercom.instance.loginIdentifiedUser()` or `Intercom.instance.loginUnIdentifiedUser()`.

![Screen Shot 2022-12-09 at 10 03 33 AM](https://user-images.githubusercontent.com/14223997/206624679-352026f2-9786-483a-9098-169e51e9bc9c.png)

**Comment by insysinfo** [comment]
> @insysinfo Make sure there is an Intercom user before displaying the Messenger. `Intercom.instance.loginIdentifiedUser()` or `Intercom.instance.loginUnIdentifiedUser()`.
> 
> ![Screen Shot 2022-12-09 at 10 03 33 AM](https://user-images.githubusercontent.com/14223997/206624679-352026f2-9786-483a-9098-169e51e9bc9c.png)

https://user-images.githubusercontent.com/70749329/206643366-fb153c8d-3de3-4209-b7de-386d57b3931d.mov


I have used registerIdentifiedUser when register OR login user..
then using Intercome.instance.displayMessagner() for display popup..

 await  Intercom.instance.registerIdentifiedUser(
          email: _userInfoModel.email,
)

i'm facing issue on Android and IOS, in flutter web platform working as well...
i've posted video below..

could you share pls any suggestion OR solution for it? @deepak786

**Comment by deepak786** [comment]
@insysinfo Please provide the reproducible sample or I suggest you give it a try to example app.

**Comment by deepak786** [comment]
I have tested the example app with the latest intercom_flutter.

```
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // TODO: make sure to add keys from your Intercom workspace.
  await Intercom.instance.initialize(
    'appId',
    androidApiKey: 'androidApiKey',
    iosApiKey: 'iosApiKey',
  );
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Intercom example app'),
        ),
        body: Center(
          child: TextButton(
            onPressed: () async {
              // NOTE:
              // Messenger will load the messages only if the user is registered
              // in Intercom.
              // Either identified or unidentified.
              // So make sure to login the user in Intercom first before opening
              // the intercom messenger.
              // Otherwise messenger will not load.
              await Intercom.instance.loginUnidentifiedUser();
              Intercom.instance.displayMessenger();
            },
            child: Text('Show messenger'),
          ),
        ),
      ),
    );
  }
}

```

And it is working fine. 
So closing this issue based on the testing. If you still face this issue, feel free to comment and provide a reproducible sample.
