### ISSUE TITLE
App crashes on first load. Only in development.

### ISSUE THREAD

**Issue by LeonardoMussato** [deepak786/intercom_flutter#276]
Hi I'm trying to figure out what's wrong in my set up. 
I'm using very good venture framework for flutter. 

When I launch the main_production.dart there are problems but the app starts without problems but when I launch the main_development.dart with flavor development the app crashes in just a few seconds...

This is the log I receive:

`W/mily.mobile.dev( 6738): Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (unsupported, reflection, allowed)
W/Intercom realtime( 6738): No realtime endpoints present so we can't connect
W/mily.mobile.dev( 6738): Accessing hidden method Landroid/net/Uri;-><init>()V (unsupported, reflection, allowed)
2
W/mily.mobile.dev( 6738): Unable to resolve Lio/intercom/android/sdk/models/Conversation$Builder; annotation class 8372
D/MediaCodecList( 6738): codecHandlesFormat: no format, so no extra checks
D/CCodec  ( 6738): allocate(c2.android.mp3.decoder)
I/Codec2Client( 6738): Available Codec2 services: "default" "software"
I/CCodec  ( 6738): setting up 'default' as default (vendor) store
I/CCodec  ( 6738): Created component [c2.android.mp3.decoder]
D/CCodecConfig( 6738): read media type: audio/mpeg
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 6738): c2 config diff is Dict {
D/CCodecConfig( 6738):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 6738):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 6738):   c2::u32 input.delay.value = 0
D/CCodecConfig( 6738):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig( 6738):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 6738): }
D/CCodec  ( 6738): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 6738): no c2 equivalents for durationUs
D/CCodecConfig( 6738): no c2 equivalents for track-id
D/CCodecConfig( 6738): no c2 equivalents for encoder-delay
D/CCodecConfig( 6738): no c2 equivalents for encoder-padding
D/CCodecConfig( 6738): no c2 equivalents for flags
D/CCodecConfig( 6738): c2 config diff is   c2::u32 coded.bitrate.value = 32000
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 11025
W/Codec2Client( 6738): query -- param skipped: index = 1107298332.
D/CCodec  ( 6738): encoding statistics level = 0
D/CCodec  ( 6738): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t bitrate = 32000
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   int32_t max-input-size = 8192
D/CCodec  ( 6738):   string mime = "audio/mpeg"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738): }
D/CCodec  ( 6738): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   string mime = "audio/raw"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738):   int32_t encoder-delay = 528
D/CCodec  ( 6738):   int32_t encoder-padding = 1584
D/CCodec  ( 6738):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 6738): }
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 6738): query -- param skipped: index = 1342179345.
W/Codec2Client( 6738): query -- param skipped: index = 2415921170.
D/C2Store ( 6738): Using DMABUF Heaps
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#488] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#488] Created output block pool with allocatorID 16 => poolID 66 - OK
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#488] Configured output block pool ids 66 => OK
I/DMABUFHEAPS( 6738): Using DMA-BUF heap named: system
3
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#488] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 6738): onLastStrongRef automatically unlinking death recipients
D/MediaCodecList( 6738): codecHandlesFormat: no format, so no extra checks
D/CCodec  ( 6738): allocate(c2.android.mp3.decoder)
I/CCodec  ( 6738): setting up 'default' as default (vendor) store
I/CCodec  ( 6738): Created component [c2.android.mp3.decoder]
D/CCodecConfig( 6738): read media type: audio/mpeg
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 6738): c2 config diff is Dict {
D/CCodecConfig( 6738):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 6738):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 6738):   c2::u32 input.delay.value = 0
D/CCodecConfig( 6738):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig( 6738):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 6738): }
D/CCodec  ( 6738): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 6738): no c2 equivalents for durationUs
D/CCodecConfig( 6738): no c2 equivalents for track-id
D/CCodecConfig( 6738): no c2 equivalents for encoder-delay
D/CCodecConfig( 6738): no c2 equivalents for encoder-padding
D/CCodecConfig( 6738): no c2 equivalents for flags
D/CCodecConfig( 6738): c2 config diff is   c2::u32 coded.bitrate.value = 32000
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 11025
W/Codec2Client( 6738): query -- param skipped: index = 1107298332.
D/CCodec  ( 6738): encoding statistics level = 0
D/CCodec  ( 6738): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t bitrate = 32000
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   int32_t max-input-size = 8192
D/CCodec  ( 6738):   string mime = "audio/mpeg"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738): }
D/CCodec  ( 6738): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   string mime = "audio/raw"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738):   int32_t encoder-delay = 528
D/CCodec  ( 6738):   int32_t encoder-padding = 1695
D/CCodec  ( 6738):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 6738): }
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 6738): query -- param skipped: index = 1342179345.
W/Codec2Client( 6738): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#77] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
I/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#77] Created output block pool with allocatorID 16 => poolID 67 - OK
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#77] Configured output block pool ids 67 => OK
3
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#77] MediaCodec discarded an unknown buffer
D/MediaCodecList( 6738): codecHandlesFormat: no format, so no extra checks
I/hw-BpHwBinder( 6738): onLastStrongRef automatically unlinking death recipients
D/CCodec  ( 6738): allocate(c2.android.mp3.decoder)
I/CCodec  ( 6738): setting up 'default' as default (vendor) store
I/CCodec  ( 6738): Created component [c2.android.mp3.decoder]
D/CCodecConfig( 6738): read media type: audio/mpeg
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 6738): c2 config diff is Dict {
D/CCodecConfig( 6738):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 6738):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 6738):   c2::u32 input.delay.value = 0
D/CCodecConfig( 6738):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig( 6738):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 6738): }
D/CCodec  ( 6738): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 6738): no c2 equivalents for durationUs
D/CCodecConfig( 6738): no c2 equivalents for track-id
D/CCodecConfig( 6738): no c2 equivalents for encoder-delay
D/CCodecConfig( 6738): no c2 equivalents for encoder-padding
D/CCodecConfig( 6738): no c2 equivalents for flags
D/CCodecConfig( 6738): c2 config diff is   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 11025
W/Codec2Client( 6738): query -- param skipped: index = 1107298332.
D/CCodec  ( 6738): encoding statistics level = 0
D/CCodec  ( 6738): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t bitrate = 64000
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   int32_t max-input-size = 8192
D/CCodec  ( 6738):   string mime = "audio/mpeg"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738): }
D/CCodec  ( 6738): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   string mime = "audio/raw"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   string mime = "audio/raw"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738):   int32_t encoder-delay = 528
D/CCodec  ( 6738):   int32_t encoder-padding = 1437
D/CCodec  ( 6738):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 6738): }
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 6738): query -- param skipped: index = 1342179345.
W/Codec2Client( 6738): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#842] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
I/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#842] Created output block pool with allocatorID 16 => poolID 68 - OK
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#842] Configured output block pool ids 68 => OK
3
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#842] MediaCodec discarded an unknown buffer
D/MediaCodecList( 6738): codecHandlesFormat: no format, so no extra checks
I/hw-BpHwBinder( 6738): onLastStrongRef automatically unlinking death recipients
D/CCodec  ( 6738): allocate(c2.android.mp3.decoder)
I/CCodec  ( 6738): setting up 'default' as default (vendor) store
I/CCodec  ( 6738): Created component [c2.android.mp3.decoder]
D/CCodecConfig( 6738): read media type: audio/mpeg
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 6738): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig( 6738): c2 config diff is Dict {
D/CCodecConfig( 6738):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig( 6738):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig( 6738):   c2::u32 input.delay.value = 0
D/CCodecConfig( 6738):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig( 6738):   string output.media-type.value = "audio/raw"
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig( 6738): }
D/CCodec  ( 6738): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 6738): no c2 equivalents for durationUs
D/CCodecConfig( 6738): no c2 equivalents for track-id
D/CCodecConfig( 6738): no c2 equivalents for encoder-delay
D/CCodecConfig( 6738): no c2 equivalents for encoder-padding
D/CCodecConfig( 6738): no c2 equivalents for flags
D/CCodecConfig( 6738): c2 config diff is   c2::u32 coded.bitrate.value = 32000
D/CCodecConfig( 6738):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig( 6738):   c2::u32 raw.sample-rate.value = 11025
W/Codec2Client( 6738): query -- param skipped: index = 1107298332.
D/CCodec  ( 6738): encoding statistics level = 0
D/CCodec  ( 6738): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t bitrate = 32000
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   int32_t max-input-size = 8192
D/CCodec  ( 6738):   string mime = "audio/mpeg"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738): }
D/CCodec  ( 6738): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 6738):   int32_t channel-count = 1
D/CCodec  ( 6738):   string mime = "audio/raw"
D/CCodec  ( 6738):   int32_t sample-rate = 11025
D/CCodec  ( 6738):   int32_t encoder-delay = 528
D/CCodec  ( 6738):   int32_t encoder-padding = 1695
D/CCodec  ( 6738):   int32_t android._config-pcm-encoding = 2
D/CCodec  ( 6738): }
I/CCodecConfig( 6738): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 6738): query -- param skipped: index = 1342179345.
W/Codec2Client( 6738): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#782] Created input block pool with allocatorID 16 => poolID 20 - OK (0)
I/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#782] Created output block pool with allocatorID 16 => poolID 69 - OK
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#782] Configured output block pool ids 69 => OK
3
D/CCodecBufferChannel( 6738): [c2.android.mp3.decoder#782] MediaCodec discarded an unknown buffer
D/TrafficStats( 6738): tagSocket(118) with statsTag=0x2caae12, statsUid=-1
I/hw-BpHwBinder( 6738): onLastStrongRef automatically unlinking death recipients
D/TrafficStats( 6738): tagSocket(119) with statsTag=0x2caae12, statsUid=-1
D/TrafficStats( 6738): tagSocket(120) with statsTag=0x2caae12, statsUid=-1
E/SurfaceSyncer( 6738): Failed to find sync for id=0
E/SurfaceSyncer( 6738): Failed to find sync for id=1
W/Parcel  ( 6738): Expecting binder but got null!
D/CompatibilityChangeReporter( 6738): Compat change id reported: 210923482; UID 10157; state: DISABLED
D/CompatibilityChangeReporter( 6738): Compat change id reported: 37756858; UID 10157; state: ENABLED
D/AndroidRuntime( 6738): Shutting down VM
E/AndroidRuntime( 6738): FATAL EXCEPTION: main
E/AndroidRuntime( 6738): Process: com.uaffamily.mobile.dev, PID: 6738
E/AndroidRuntime( 6738): java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{9d92b28 V.E...... ......ID 0,0-1080,2220 #7f08018d app:id/intercom_overlay_root}
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:349)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:324)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:299)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:242)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:249)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.AbstractComposeView.createComposition(ComposeView.android.kt:194)
E/AndroidRuntime( 6738): 	at androidx.compose.ui.platform.ComposeView.setContent(ComposeView.android.kt:420)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.m5.notification.InAppNotificationCardKt.addTicketHeaderToCompose(InAppNotificationCard.kt:55)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.overlay.ChatNotification.populateViewsWithData(ChatNotification.java:111)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.overlay.ChatNotification.display(ChatNotification.java:71)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:184)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:90)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:79)
E/AndroidRuntime( 6738): 	at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:30)
E/AndroidRuntime( 6738): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
E/AndroidRuntime( 6738): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3352)
E/AndroidRuntime( 6738): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
E/AndroidRuntime( 6738): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
E/AndroidRuntime( 6738): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
E/AndroidRuntime( 6738): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
E/AndroidRuntime( 6738): 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
E/AndroidRuntime( 6738): 	at android.view.Choreographer.doFrame(Choreographer.java:832)
E/AndroidRuntime( 6738): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
E/AndroidRuntime( 6738): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 6738): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6738): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6738): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6738): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime( 6738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process ( 6738): Sending signal. PID: 6738 SIG: 9
Lost connection to device.`

If you needed it I can give you more info, just let me know.
Thanks in advance!

**Comment by deepak786** [comment]
@LeonardoMussato It seems to be a similar issue as https://github.com/v3rm0n/intercom_flutter/issues/270
Please make sure to extend Android `MainActivity` with `FlutterFragmentActivity` instead of `FlutterActivity`.
