### ISSUE TITLE
Handling the exceptions on the Flutter side

### ISSUE THREAD

**Issue by yadaniyil** [deepak786/intercom_flutter#277]
When the user is not registered and I call `_intercom.displayMessenger()` I see 
`Intercom was presented but there was no user registered on this device.Please call registerUnidentifiedUser() or registerIdentifiedUser(Registration).` in my logs. 

But I cannot catch any errors with try/catch.

Do I do something wrong or I cannot catch the exception on the Flutter side?

**Comment by deepak786** [comment]
@yadaniyil You can't catch this error. It is a requirement that there must be an Intercom user session before displaying the messenger.

**Comment by yadaniyil** [comment]
Thanks @deepak786

**Comment by Bojan227** [comment]
> @yadaniyil You can't catch this error. It is a requirement that there must be an Intercom user session before displaying the messenger.

@deepak786 How to init a user session?

**Comment by deepak786** [comment]
@Bojan227 You can create a user session using [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html) or [loginUnidentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginUnidentifiedUser.html)

**Comment by Bojan227** [comment]
> @Bojan227 You can create a user session using [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html) or [loginUnidentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginUnidentifiedUser.html)

@deepak786 can i use any user_id?
Probably should be related to the backend user id.
