### ISSUE TITLE
Open a conversation from a button

### ISSUE THREAD

**Issue by ajoseerazo** [deepak786/intercom_flutter#278]
Hi. I really like this library. Congratulations.

I'm trying to achieve this. I would like to know wether is possible to open an specific conversation clicking a Button in my application. I've tried in multiple ways but I couldn't. It would be great if I can achieve this.

Thank in advance.

**Comment by deepak786** [comment]
Hi @ajoseerazo 
Great to hear that you like the package.
Currently, there is no way to open a specific conversation. The intercom itself opens the specific conversation from the notification click as per my knowledge. But the corresponding API is not exposed.

**Comment by ajoseerazo** [comment]
Ok, I understand.

Thank you so much and congratulations for the great work!
