### ISSUE TITLE
[REQUEST] Create option to open directly to a message

### ISSUE THREAD

**Issue by OgunwoleOluwatobi** [deepak786/intercom_flutter#281]
This is request to be able to open a message by an ID without having the option to return to previous messages like the implementation we have currently when a notification is recieved

**Comment by deepak786** [comment]
@OgunwoleOluwatobi I didn't understand your point. Could you please elaborate?

**Comment by OgunwoleOluwatobi** [comment]
I'm asking if we can have the option to open a message directly like how the "open by ArticleID" functions. So we can directly lauch a message without going through the message list.

I had a senerio where when a push notification came in, it open the message but the user had the option to go back to the message history but at that point i did not want the user to have access to the history hence my request on this.

I guess another option would be to be able to disable the back action on a message screen. If you understand my usecase and have a way around that I'n currently unaware of, I'll appreciate it.

**Comment by deepak786** [comment]
@OgunwoleOluwatobi I believe there is no such API exposed by the Intercom.
We can't open the particular message or disable the back action on message screen. This is Internally handled by the SDK.

For more information, you can reach Intercom support team.
