### ISSUE TITLE
Android: Open messenger from background notification click

### ISSUE THREAD

**Issue by doriansabo** [deepak786/intercom_flutter#284]
Is it possible to immediately open the chat dialog after the user clicks on the notification while the app is in the background?

On android If the user clicks on the notification the app will open and display the chat icon, clicking on the chat icon the chat dialog will be opened. Is there a way to avoid the need for clicking on the chat icon? So the user will be redirected to the chat dialog immediately after clicking on the background notification.

On iOS it will immediately open the chat dialog.

chat icon:
![Screenshot at Feb 02 13-32-47](https://user-images.githubusercontent.com/105852695/216326547-48b07243-8c80-45ff-804a-e403839841d5.png)

chat dialog:
![Screenshot at Feb 02 13-38-17](https://user-images.githubusercontent.com/105852695/216327124-fd6b0815-778d-4811-8f8c-7f3d300693fd.png)

**Comment by deepak786** [comment]
@doriansabo I would suggest calling this method `Intercom.instance.handlePushMessage()` when your app comes to the foreground. This will open the chat dialog. Maybe you need to add the Android platform check so that it will not affect iOS.

Documentation: https://developers.intercom.com/installing-intercom/docs/push-notifications-android#step-7-open-intercom-conversations-from-fcm

**Comment by doriansabo** [comment]
> @doriansabo I would suggest calling this method `Intercom.instance.handlePushMessage()` when your app comes to the foreground. This will open the chat dialog. Maybe you need to add the Android platform check so that it will not affect iOS.
> 
> Documentation: https://developers.intercom.com/installing-intercom/docs/push-notifications-android#step-7-open-intercom-conversations-from-fcm

Can that method open an already ongoing chat dialog with support?

**Comment by deepak786** [comment]
I believe this method will just act on the data that the app receives from the push notification. Similar to when you click on the "chat icon" in the above screenshots.
If the app has no notification data then this function probably will not do anything.

**Comment by doriansabo** [comment]
@deepak786 Thank you for the response. The `Intercom.instance.handlePushMessage()` solved my issue.

**Comment by deepak786** [comment]
@doriansabo If you can share a code sample about how you make use of it then it will be helpful for others.
