### ISSUE TITLE
Mobile Carousels

### ISSUE THREAD

**Issue by churchnotesapp** [deepak786/intercom_flutter#285]
Hey! Does Intercom Flutter currently support Mobile Carousels?

https://www.intercom.com/help/en/articles/4605339-launch-mobile-carousels-from-a-button-in-your-mobile-app

**Comment by deepak786** [comment]
Yes, see the documentation
https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/displayArticle.html
https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/displayCarousel.html
