### ISSUE TITLE
Android [7.6.2] hideMessenger method doesn't work

### ISSUE THREAD

**Issue by doriansabo** [deepak786/intercom_flutter#286]
The `await Intercom.instance.hideMessenger();` dones't close the intercom screen on android.

On iOS it works as expected.

**Comment by deepak786** [comment]
@doriansabo How did you test this?
Because once the Intercom messenger is opened, you cannot interact with any of the views inside your app. It is overlayed by the messenger.

**Comment by doriansabo** [comment]
@deepak786 I'm calling this method before I put the app in the background. I have a problem when the intercom chat is already opened, and the user puts the app in the background and then receives a push notification, by clicking on it it opens another intercom chat. So I'm trying to close the chat when the app is in the background.

**Comment by deepak786** [comment]
Reproducible sample:

```
return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: TextButton(
          onPressed: () async {
            // NOTE:
            // Messenger will load the messages only if the user is registered
            // in Intercom.
            // Either identified or unidentified.
            // So make sure to login the user in Intercom first before opening
            // the intercom messenger.
            // Otherwise messenger will not load.
            await Intercom.instance.displayMessenger();

            // Hide the messenger after 5 seconds
            Future.delayed(
              Duration(seconds: 5),
              () {
                print("Hiding messenger");
                Intercom.instance.hideMessenger();
              },
            );
          },
          child: Text('Show messenger'),
        ),
      ),
    );
```

When clicking "Show messenger", Messenger is displayed and after 5 seconds there is a print on the console "Hiding messenger". But the messenger is not hidden.

Works fine with `intercom_flutter: 7.5.0`. But Starting Intercom Android SDK v14 (intercom_flutter: 7.6.0), it is not working.

**Comment by doriansabo** [comment]
@deepak786 What is the procedure for this kind of bug? Can I expect a fix for this?

**Comment by deepak786** [comment]
I have already reported the issue to Intercom support. They are checking. 
I don't know when it will be solved. We just have to wait for the fix in the Native SDK.

**Comment by deepak786** [comment]
Use `intercom_flutter: 7.6.7`.
