### ISSUE TITLE
Intercom is restarting the app when click on back button from the messenger which is displayed from in-app message.

### ISSUE THREAD

**Issue by MadavaramRamesh** [deepak786/intercom_flutter#303]
<img width="404" alt="Screenshot 2023-05-05 at 1 44 36 PM" src="https://user-images.githubusercontent.com/26106180/236438114-b81d1cd8-9633-4488-a3ae-f8b53584321e.png">

**Comment by deepak786** [comment]
@MadavaramRamesh This was resolved in `intercom_flutter: 7.6.9`. See https://github.com/v3rm0n/intercom_flutter/issues/279

Which version are you using?
