### ISSUE TITLE
Issues displaying message

### ISSUE THREAD

**Issue by JycTheDev** [deepak786/intercom_flutter#305]
For reason yet known, displaying of message is no longer working

i have confirmed this steps
1. Accurate id
2. Accurate Android Key
3. Accurate IOS key
4. Initializing SDK
5. Configuring the android module as stated [here](https://pub.dev/packages/intercom_flutter)

but displaying of message still fails on both Android and IOS

![simulator_screenshot_70BDAD98-53A1-484C-A201-5D8FAC0753A7](https://github.com/v3rm0n/intercom_flutter/assets/29983299/fe6bd652-d958-4030-ad34-92122ea1a393)

**Comment by JycTheDev** [comment]
Apparently this issue has to do with users account login in to the app.

**Comment by NarekManukyan** [comment]
@jbankz Have you found a solution? It worked for me a week ago, but now it stopped working with the same message.

```    
    await Intercom.instance.loginUnidentifiedUser();
    await Intercom.instance.displayMessenger();
```
