### ISSUE TITLE
loginUnidentifiedUser should return intercom user id

### ISSUE THREAD

**Issue by simplenotezy** [deepak786/intercom_flutter#313]
When running `loginUnidentifiedUser` it would be helpful it the method returned the Intercom User Id (as it is shown in Intercom chats).

The reason is, it would make it easier to debug issues for unidentified users in our app - as we could use the returned intercom id as the user identifier for bug/crash reports. That way, we could easily investigate if a user contacts us via chat with an issue, as we could simply check the logs for the given intercom user id.

Currently we have no way of checking logs for unidentified users

**Comment by deepak786** [comment]
@simplenotezy It's not possible. Intercom SDK API does not provide the user_id or any identification of the user.

**Comment by simplenotezy** [comment]
@deepak786 I see - what a shame.

What do you think about instead generating a random UUID on the client for `unidentifiedUsers` and then using `updateUser` to set any needed information?

**Comment by deepak786** [comment]
@simplenotezy Yes, you can try that.
