### ISSUE TITLE
[Android]: Do not request push notification permission during initialization.

### ISSUE THREAD

**Issue by zhujiageng** [deepak786/intercom_flutter#314]
Calling ```IntercomFlutterPlugin.initSdk``` will immediately request for push notification permission, which is not what I want. I want to request push notification permission to users at the appropriate time.

**Comment by deepak786** [comment]
`IntercomFlutterPlugin.initSdk` only initializes the Intercom Android SDK. Besides it is not doing anything.

**Comment by zhujiageng** [comment]
Thank you. It's really strange that once the initialization method of Intercom is called, whether it is called on the Android side or on the Dart side, push notification permission will be requested immediately upon starting. If neither side calls it, push notification permission will not be requested.

**Comment by deepak786** [comment]
I ran the example app on an Android 13 device. But I didn't see the notification permission request dialog.
Can you also try the example app at your end?https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter/example

**Comment by zhujiageng** [comment]
This demo does not automatically request push permission when it starts up.

**Comment by deepak786** [comment]
So there must be something in your code that is asking for the notification permission. Can you share the reproducible code?

**Comment by deepak786** [comment]
@zhujiageng Do you have any update on this? Otherwise, we can close this issue.

**Comment by bromar2292** [comment]
I am having the exact same issue, only happening in the android, ios is fine

**Comment by deepak786** [comment]
@bromar2292 Can you provide the reproducible sample?

**Comment by bromar2292** [comment]
my issue is in flutter, when Intercom.instance.initialize(AppId!,
        iosApiKey: config.iApiKey, androidApiKey: config.ApiKey);
        is called on start up
        in ios I don't get a request notification permissions but in android I do, and if i comment this code out i dont get a permissions request in android.
        
        sorry i am unable to reproduce a sample

**Comment by deepak786** [comment]
@bromar2292 Do you have the same issue with the example app https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter/example?

**Comment by bromar2292** [comment]
i should also mention this only happens on the first installation of the app, it doesn't happen again after when you reopen the app, i will try that example, if you uninstall the app and reopen it, it will come back

**Comment by bromar2292** [comment]
hi i solved the issue it was here if anyone else finds the same problem, it was android related not intercom 
[https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps](url)

**Comment by deepak786** [comment]
@bromar2292 So basically, you were targeting Android 12 or lower. So Thats why the permission dialog was visible to you automatically.
And now you target Android 13 so there is no permission dialog at run time.

right?

**Comment by deepak786** [comment]
Solution: Update your targetSdkVersion and compileSdkVersion to 33.
See for more info https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps
