### ISSUE TITLE
Network request succeeded but the response was ignored

### ISSUE THREAD

**Issue by artemsorochan** [deepak786/intercom_flutter#317]
Trying to call loginIdentifiedUser() throws the issue: Network request succeeded but the response was ignored.

5  ???                            0x0 MethodChannelIntercomFlutter.loginIdentifiedUser + 56 (method_channel_intercom_flutter.dart:56)

Is it a bug? If not could you please clarify what does it mean?

intercom_flutter: ^7.6.9
Flutter (Channel stable, 3.10.2)

**Comment by deepak786** [comment]
@artemsorochan It seems that there is an exception when you are trying to log in to the Intercom with userId.
https://github.com/v3rm0n/intercom_flutter/blob/82adf10c83a7a8206f3051b77dbf597351d8671f/intercom_flutter_platform_interface/lib/method_channel_intercom_flutter.dart#L56

Can you share the reproducible code?

**Comment by artemsorochan** [comment]
@deepak786

**Comment by artemsorochan** [comment]
final user = _authBloc.state.user;

final hash = await _apiService.getHash();

await _intercom.logout();
await _intercom.setUserHash(hash);
await _intercom.loginIdentifiedUser(
userId: user.id,
statusCallback: IntercomStatusCallback(onFailure: (e) => add(ThrowException(e, StackTrace.current))),
);

await _intercom.updateUser(
userId: user.id,
name: user.name,
email: user.email,
customAttributes: getCustomAttribution(
user: _authBloc.state.user,
),
language: deviceLocale,
signedUpAt: _authBloc.state.user.metadata?.creationTime?.millisecondsSinceEpoch,
statusCallback: IntercomStatusCallback(onFailure: (e) => add(ThrowException(e, StackTrace.current))),
);
await _intercom.setInAppMessagesVisibility(IntercomVisibility.visible);
if (event.callback != null) {
add(event.callback!);
}
