### ISSUE TITLE
how to add clear all button for intercom messages ,

### ISSUE THREAD

**Issue by AhkamKhallaf** [deepak786/intercom_flutter#319]
I wanna to know  how to add clear all button for intercom messages ,
i use intercom_flutter: ^7.6.8 with flutter , 
i wanna to add clear buttons above thee  intercom   messages 

![Simulator Screen Shot - iPhone 13 - 2023-06-21 at 11 16 36](https://github.com/v3rm0n/intercom_flutter/assets/31520379/0eea7006-5982-4685-9d3b-b828c0ec3cd2)

**Comment by deepak786** [comment]
@AhkamKhalaaf I don't think there is any way for this as it is internal in the SDK but you can hide the in-app messages to display in your app using https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/setInAppMessagesVisibility.html

**Comment by deepak786** [comment]
@AhkamKhalaaf This is the reply from Intercom:

```
I can confirm that is currently not possible add a clear button to close unread messages. However, you can prevent in app messages from popping up in certain parts of your app by calling (Android example):
Intercom.client().setInAppMessageVisibility(Visibility.GONE)
You can find it documented [here](https://developers.intercom.com/installing-intercom/docs/using-intercom-android#temporarily-hide-notifications). That would be the closest you could get.
```
