### ISSUE TITLE
Open Intercom messenger with certain intents

### ISSUE THREAD

**Issue by kean-fetchpet** [deepak786/intercom_flutter#327]
Hi @deepak786,

Thank you for your awesome work on this plugin. Really appreciate it and got you a few coffee. 

Just wondering if there is a way i can open intercom chat with certain intents. I.e. i know where users came from (i.e. after certain buttons) and therefore know what help we can offer them instead of showing them the broader question sets we ask when they first come to the chat.

**Comment by deepak786** [comment]
@kean-fetchpet Glad to know that you like the plugin.

> Just wondering if there is a way i can open intercom chat with certain intents. I.e. i know where users came from (i.e. after certain buttons) and therefore know what help we can offer them instead of showing them the broader question sets we ask when they first come to the chat.

I'm not sure if there is a similar API for the same functionality in the native SDK.

**Comment by kean-fetchpet** [comment]
@deepak786 cannot seem to find it. I know there is something for web elements. You can customise your messenger so that it can "provide support from a button on your website". But i am not sure if there is one for mobile app.

**Comment by kean-fetchpet** [comment]
is there a way to send a certain message to intercom chat? I know there is a function displayMessageComposer to pre-fill the message but it does not send the message.

**Comment by deepak786** [comment]
> I know there is something for web elements. You can customise your messenger so that it can "provide support from a button on your website".

@kean-fetchpet You can also open the Intercom messenger from any button in the mobile app. See https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/displayMessenger.html
If this is not what you are looking for, please share some references regarding "You can customise your messenger so that it can "provide support from a button on your website"".


> is there a way to send a certain message to intercom chat? I know there is a function displayMessageComposer to pre-fill the message but it does not send the message.

No, there is no way to send a message directly. The user has to click on send button by itself.

**Comment by deepak786** [comment]
@kean-fetchpet I contacted Intercom and this is the reply from them.

```
That's also not possible at the moment, as you stated in the comment. The only way to actually send a message in a conversation is via our [Rest API](https://developers.intercom.com/intercom-api-reference/reference/createconversation).
But I'll make sure to add these as feature requests to our Product Team. Thank you for sharing them with us 🙏
```

**Comment by kean-fetchpet** [comment]
@deepak786 Thanks for following it up. I contacted Intercom as well and unfortunately there is not a feature to allow that.
