### ISSUE TITLE
How to Identify a User by Both User ID and Email?

### ISSUE THREAD

**Issue by masterwok** [deepak786/intercom_flutter#329]
The [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html) method only allows consumers to suppy either an email or user ID as a parameter. 

I'd like to track authenticated users by both their email and user ID. According to the native [Android documentation](https://developers.intercom.com/installing-intercom/docs/using-intercom-android) on the Intercom website this is possible using the `withEmail(..)` and `withUserId(..)` methods on the `Registration` builder class. 

How do I ensure my user is being tracked by both their user ID and email address similarly to the native Android library?

**Comment by deepak786** [comment]
@masterwok Register your user with user_id using [loginIdentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginIdentifiedUser.html)

After that update your user using [updateUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/updateUser.html). Here you can pass the email.

```
Intercom.instance.loginIdentifiedUser(userId: userID)
.then((value) async {
    // now update the user in Intercom
    return Intercom.instance.updateUser(
      email: email
    );
});
```

**Comment by masterwok** [comment]
Thank you @deepak786 !
