### ISSUE TITLE
set recent pageviews on mobile device

### ISSUE THREAD

**Issue by viniciusmoreiraa** [deepak786/intercom_flutter#33]
In the web function there is a recent pageview attribute, which shows the history of pages navigated by the user, does the plugin for flutter have this function?

**Comment by Zazo032** [comment]
This plugin currently does not support the web platform, as Flutter for Web is still in Technical Preview. I don't think this is possible in Android/iOS apps.

**Comment by deepak786** [comment]
@viniciusmoreiraa This is not possible in Android/iOS.
But you can use Intercom Events for this purpose.
