### ISSUE TITLE
Logout needs to be called before loginIdentifiedUser

### ISSUE THREAD

**Issue by aprzedecki** [deepak786/intercom_flutter#330]
Occurs only on Android: `logout` method needs to be called before `loginIdentifiedUser` for the same user.
Otherwise it throws: 

```
Exception: errorCode: 3002, errorMessage: ERROR - Failed to register user. We already have a registered user. If you are attempting to register a new user, call logout() before this.
```

intercom_flutter version 7.8.1

Test device
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.0)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by deepak786** [comment]
@aprzedecki I believe it is working as expected.
I tested the older SDK versions also and the behavior is the same.

Could you please explain your use case?

**Comment by aprzedecki** [comment]
> @aprzedecki I believe it is working as expected. I tested the older SDK versions also and the behavior is the same.
> 
> Could you please explain your use case?

My case is the simplest - example app from the repo.
If logout is always required before the login (otherwise SDK throws exception) why is it not part of the method itself ?

**Comment by deepak786** [comment]
@aprzedecki But the exception occurs only if there is already an Intercom user in the session and you still trying to log in.

**Comment by aprzedecki** [comment]
> @aprzedecki But the exception occurs only if there is already an Intercom user in the session and you still trying to log in.

Is the session stored somewhere even after app restart ?

**Comment by deepak786** [comment]
Intercom handles the session internally.

**Comment by aprzedecki** [comment]
Is there a way to check that ? I think you should correct the example in the repo - try it out on Android after user login and app restart restart.

**Comment by deepak786** [comment]
There is no way to check the session. I have already tested it.

What I can suggest to you is to ignore the statusCallback parameter or use it just for logging the output from the request.

```
await Intercom.instance.loginIdentifiedUser();
// DO the rest of the functionality here ... such as display messenger
Intercom.instance.displayMessenger();
```

**Comment by aprzedecki** [comment]
ok, all clear - thanks 👌
