### ISSUE TITLE
Messenger Not Rendering Correctly on iOS

### ISSUE THREAD

**Issue by masterwok** [deepak786/intercom_flutter#334]
The mesenger on iOS isn't rendering correctly. The "Messages" and "Send us a message" options are missing their white backgorund colors.

<img width="402" alt="image" src="https://github.com/v3rm0n/intercom_flutter/assets/5054978/44b5f982-0c04-4291-8d8b-70f8f2409bc9">

The messenger on Android is rendering as expected:

<img width="460" alt="Screenshot 2023-07-21 at 11 23 10 AM" src="https://github.com/v3rm0n/intercom_flutter/assets/5054978/85b9e915-1651-4ecd-992a-ecee90c1c22d">

What would cause the iOS messenger to render incorrectly? I'm using `intercom_flutter: 7.8.2` within the application.

**Comment by Zazo032** [comment]
What Flutter and iOS versions are you using? Did you check that the theming is set properly on the Intercom side?

**Comment by masterwok** [comment]
I'm using iOS 16.4 in my simulator and my physical device is iOS 16.5.1. Both of these device are presenting with this issue. The `intercom_flutter` library is `7.8.2` which according to the release notes is using the native iOS library version `15.0.3`. I'm using Flutter 3.10.5

Looking at the Intercom side for theme configuration everything looks in alignment between iOS and Android. I didn't see any options for configuring the background color of the help items. Also, on iOS the in-chat buttons are invisible but can still be tapped (they appaer correctly on Android).

<img width="425" alt="image" src="https://github.com/v3rm0n/intercom_flutter/assets/5054978/9ee4b08c-fc14-4d48-a7b1-89fb88e2c409">

This is how we have the styling configured within the Intercom dashboard.

<img width="1564" alt="image" src="https://github.com/v3rm0n/intercom_flutter/assets/5054978/d587ecdf-8fbb-4a60-952b-fdd45b3a3cd5">

**Comment by masterwok** [comment]
I'm using Flutter 3.10.5

**Comment by masterwok** [comment]
So I just ran the same project within this repository and everything is working as expected. This means that there's something in my project that's interfering with some sort of global style or theme that Intercom uses. I'm familiar wth Android but iOS is very much still unfamiliar ground for me. 

Do you know how I might determine what theme or configuration in my project might be interfering with Intercom?

**Comment by masterwok** [comment]
Any help on this issue would be greatly appriciated. I'm not an iOS developer myself so I'm not sure what could be colliding with the Intercom package.

**Comment by deepak786** [comment]
@masterwok Can you please send a message to the Intercom support team? They will be able to check your Intercom settings.

**Comment by masterwok** [comment]
I've reached out to them but they're not helping. 

![image (4)](https://github.com/v3rm0n/intercom_flutter/assets/5054978/f0ac9034-a92b-4eee-ad04-c4a1775253a2)

Could the issue be caused by how we're initializing our FlutterViewController on iOS?


```swift
    override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        self.flutterViewController = FlutterViewController();
        setUpMethodChannels(controller: flutterViewController!);
        self.window = UIWindow.init(frame: UIScreen.main.bounds)

        navigationController = UINavigationController.init(rootViewController: self.flutterViewController!)
        navigationController?.setNavigationBarHidden(true, animated: false)

        self.window.rootViewController = navigationController
        self.window.makeKeyAndVisible()
        
        guard
            let dictionary = Bundle.main.infoDictionary,
            let apiKey = dictionary["GooglePlacesApiKey"] as? String
        else {
            return false
        }

        GMSServices.provideAPIKey(apiKey)

        GeneratedPluginRegistrant.register(with: self)

        return super.application(application, didFinishLaunchingWithOptions: launchOptions);
    }
```

**Comment by deepak786** [comment]
@masterwok I'm not sure if the above code snippet is the cause of the problem. But you said that the example app is working fine on your end. Can you try doing the same thing as above (initializing FlutterViewController) in the example app and see if there is the same issue?

**Comment by masterwok** [comment]
@deepak786 I tried this shortly after posting and it had no effect on the sample application. I've also tried removing all dependcies and code from our application and the issue still persists. I'm starting to think maybe this has something to do with how our ios native project is configured but I'm not sure what would cause this.

The intercom_flutter package works fine when I create a new project. We're using flavors in our build configuration but I'm not sure what impact that might have. Do you happen to know of any iOS project settings that might cause this issue?

**Comment by deepak786** [comment]
@masterwok Compare the `Info.plist` file of your project and the new project. Maybe you will find something.

**Comment by masterwok** [comment]
Thank you! This amoung other changes to our Info.plist resolved our issue.
