### ISSUE TITLE
Cannot open messenger for the first time

### ISSUE THREAD

**Issue by NaarGes** [deepak786/intercom_flutter#336]
Hi,
I'm using `loginIdentifiedUser` to log user in the intercom.
When I login for the first time app opens after installation, intercom messenger page is not loading (stuck shimmering) but when I close and reopen the app, problem is fixed.
I'm also seeing this error each time I call `loginIdentifiedUser`:

```
E/Intercom(14407): Failed to register or update user: {"type":"error.list","request_id":random number,"errors":[{"code":"hmac_mismatch","message":"Failed Identity Verification check"}]}
``` 

https://community.intercom.com/apps-integrations-25/chat-not-starting-connecting-when-the-android-app-is-running-for-the-first-time-202

**Comment by deepak786** [comment]
@NaarGes Do you have identity verification enabled on Intercom? If yes then make sure you are using the correct hash with the setUserHash API
https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/setUserHash.html

**Comment by NaarGes** [comment]
@deepak786  Thank you for your response, I fixed the issue by moving `Intercom.instance.loginIdentifiedUser` after `Intercom.instance.setUserHash`

according to this document:
https://developers.intercom.com/installing-intercom/docs/ios-identity-verification

"When your iOS app initializes Intercom if the user is identified (i.e., you have a user id or email address), pass in a String of the HMAC returned from your server's authentication call. This should be called before any registration calls"
