### ISSUE TITLE
Displaying article showing web launcher icon.

### ISSUE THREAD

**Issue by Tristannos** [deepak786/intercom_flutter#338]
When i open a specific article on my mobile device directly, it will show the open live chat widget.

This will only happen if you open article directly. If you open it trough the main popup it does not show.

![SCR-20230804-ksn](https://github.com/v3rm0n/intercom_flutter/assets/55278228/595efe73-241e-47ff-bc4b-107a33e18c97)

**Comment by deepak786** [comment]
@Tristannos Have you added your articles in a collection? If not then add them in collection and try.

As per my knowledge, If your Article is not added to any Collection then the issue arises. But if the article is added to any collection then there is no such issue.

**Comment by deepak786** [comment]
@Tristannos Have you tried the above solution?

**Comment by Tristannos** [comment]
Yeah that worked!

Thanks A lot!
