### ISSUE TITLE
Android app crashes with an error

### ISSUE THREAD

**Issue by farawehassan** [deepak786/intercom_flutter#339]
D/AndroidRuntime(16364): Shutting down VM
E/AndroidRuntime(16364): FATAL EXCEPTION: main
E/AndroidRuntime(16364): Process: com.spantom.jeroid, PID: 16364
E/AndroidRuntime(16364): java.lang.RuntimeException: Unable to instantiate service io.maido.intercom.PushInterceptService: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/base.apk"],nativeLibraryDirectories=[/data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/lib/arm64, /data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(16364): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4078)
E/AndroidRuntime(16364): 	at android.app.ActivityThread.access$1700(ActivityThread.java:236)
E/AndroidRuntime(16364): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1939)
E/AndroidRuntime(16364): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16364): 	at android.os.Looper.loop(Looper.java:264)
E/AndroidRuntime(16364): 	at android.app.ActivityThread.main(ActivityThread.java:7581)
E/AndroidRuntime(16364): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16364): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(16364): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
E/AndroidRuntime(16364): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.maido.intercom.PushInterceptService" on path: DexPathList[[zip file "/data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/base.apk"],nativeLibraryDirectories=[/data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/lib/arm64, /data/app/com.spantom.jeroid-FHAMREBtjVM-GH6peQNSNw==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(16364): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(16364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(16364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(16364): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(16364): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime(16364): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4073)
E/AndroidRuntime(16364): 	... 8 more

**Comment by deepak786** [comment]
Please check the solution in https://github.com/v3rm0n/intercom_flutter/issues/228

**Comment by farawehassan** [comment]
> Please check the solution in #228

Thank you, I have removed the Service tag from the manifest file and also commented out intercom.handlePush(remoteMessage.data) for push notifications.

Hopefully I don't have any crash reports further.
