### ISSUE TITLE
Does this work with OneSignal push notification?

### ISSUE THREAD

**Issue by jasonlaw** [deepak786/intercom_flutter#34]
Hi @v3rm0n,

Does this work with OneSignal push notification?

Thanks in advance.

**Comment by Zazo032** [comment]
As far as I know, OneSignal support is not available in this plugin. Only Firebase in Android. Feel free to work on it and submit a PR, it would be highly appreciated.

**Comment by Spikes042** [comment]
Please note that Intercom themself does not support OneSignal. If you're sending push notifications through OneSignal you can just use their [flutter SDK](https://pub.dev/packages/onesignal_flutter). Totally has nothing to do with Intercom
