### ISSUE TITLE
Intercom in iOS don't open the URL as a regular link in Safari

### ISSUE THREAD

**Issue by vinhdn** [deepak786/intercom_flutter#346]
Hi,
I get an issue when I build my Flutter with intercom_flutter v7.8.4 in iOS
When the supporter sends a message include an URL to user (such as: `https://mywebsite.com/form`), user clicks on this url the Intercom screen is disappeared.
And in Flutter app will be get an action open new Router with name is `/form.`

Please help us take a look. If anything needs to be clear from our side, please let us know.

**Comment by vinhdn** [comment]
I updated my AppDelegete file follow the Deep Linking setup - https://developers.intercom.com/installing-intercom/docs/ios-deep-linking#universal-link

- Return `false` from the method: `application:continueUserActivity:restorationHandler:` 
- And return `false` from the method: `application:openURL:sourceApplication:annotation:`

**Comment by deepak786** [comment]
Do you have `mywebsite.com` as IntercomUniversalLinkDomains?
Can you try the message with another link different from your IntercomUniversalLinkDomains?

**Comment by vinhdn** [comment]
Can't reproduce on v7.8.5.
