### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by LvDj** [deepak786/intercom_flutter#348]
I need help.

When I add intercom_flutter, I get an error

error:
Problems reading data from Binary store in /Users/xxx/.gradle/.tmp/gradle5489534306810961670.bin offset 1119968 exists? true
Problems loading the resolution results (0.008 secs). Read 1174 values, last was: 5
Corrupt serialized resolution result. Cannot find selected component (44620) for releaseVariantReleaseRuntimePublication -> androidx.lifecycle:lifecycle-process:2.4.1

**Comment by deepak786** [comment]
Seems that it is a Gradle issue
https://github.com/gradle/gradle/issues/14220

Maybe try upgrading the Gradle version. or I would say try the [example app](https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter/example) and see if it builds fine. If yes, then use the same gradle configuration as the example app.
