### ISSUE TITLE
method logout close standard launcher 

### ISSUE THREAD

**Issue by marcuscorreasmash** [deepak786/intercom_flutter#349]
When i call logout method, the standard launcher on the bottom right-hand side of the screen is closed on android. Even if i call after the method: Intercom.instance.setLauncherVisibility(IntercomVisibility.visible); 

But, on flutter web with same source code,  hes continue showing in anonymous user and can see and use.

How i can continue open the standard launcher on the bottom right if call logout method on android?

thank you

**Comment by deepak786** [comment]
@marcuscorreasmash I believe it is the expected functionality.
On the Mobile app, you cannot use Intercom without the user being logged in. 
But on the web, you can use it without login as well.

Probably this is the reason.
