### ISSUE TITLE
Intercom Visitor

### ISSUE THREAD

**Issue by kean-fetchpet** [deepak786/intercom_flutter#361]
Is it possible to register as a visitor instead of a user? Thanks.

**Comment by deepak786** [comment]
@kean-fetchpet It's not possible. But you can use [loginUnidentifiedUser](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/loginUnidentifiedUser.html)

You cannot use the Intercom in the mobile app without the user being registered either identified or unidentified.
