### ISSUE TITLE
[iOS] Conversation not loaded when message is received

### ISSUE THREAD

**Issue by asijoumi** [deepak786/intercom_flutter#368]
Hi !

I have some issue: the conversation with a user is not loaded when he clicks on the message alert.

![Simulator Screenshot - iPhone 14 Pro - 2023-11-04 at 10 43 56](https://github.com/v3rm0n/intercom_flutter/assets/25631702/9e24783a-8d2c-4100-8c44-5049dbe616b8)

![Simulator Screenshot - iPhone 14 Pro - 2023-11-04 at 10 43 59](https://github.com/v3rm0n/intercom_flutter/assets/25631702/2f32b7a9-7af8-4b97-b041-ecb667000dc6)

The first screen shows a message `Here ?`, but when I click on this message, the conversation isn't loaded.

I'm currently with : `intercom_flutter: ^8.0.3` and `platform :ios, '13.0'`

Note: it works normally on Android, this bug is just for iOS.

Thanks 😄

**Comment by deepak786** [comment]
@asijoumi Can you try the latest version `intercom_flutter: 8.0.4`. It uses iOS SDK version [16.2.3](https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md#1623).

**Comment by asijoumi** [comment]
Hi @deepak786,

It is working ! Thank you 😃 

Aimen
