### ISSUE TITLE
Update user avatar

### ISSUE THREAD

**Issue by abdallah-gaber** [deepak786/intercom_flutter#384]
Any way can I update the user avatar?

**Comment by deepak786** [comment]
I believe there is no particular API for that.

**Comment by abdallah-gaber** [comment]
Thank you for you response @deepak786 
Can we add it to the "Feature Request" list at least or to know the probability to have this feature in the near future?

**Comment by deepak786** [comment]
This is not the right platform for the feature requests. Please submit the ticket to [Intercom support.](https://www.intercom.com/)
