### ISSUE TITLE
Certain Post type messages get stuck on Android with no way to dismiss

### ISSUE THREAD

**Issue by Morlocci** [deepak786/intercom_flutter#386]
We've noticed an issue on Android (doesn't happen on iPhones) devices on our Flutter app. Whenever a Post type message is created through Proactive Support, the message snipper will get stuck on our app. I managed to reproduce this issue consistently, with the following reproduction steps:

- Samsung A04s (Android 10)
- intercom_flutter package: 8.0.4

**Reproduction steps:**
1. Go to Intercom and create a new Proactive support message
2. Create a new "Post" type message to be sent to your test app
3. Choose any format type
4. Choose any reply type
5. Choose one: Sent as
    a. snippet
    b. badge
6. Open the app and wait for the snippet message to be received
7. Try to click on it or dismiss it

**Expected behaviour**
You are able to dismiss the message

**Actual Behaviour**
The message is stuck with no ability to dismiss it

**Comment by deepak786** [comment]
@Morlocci Make sure your Android MainActivity extends from `FlutterFragmentActivity`.
See https://github.com/v3rm0n/intercom_flutter/issues/351

**Comment by deepak786** [comment]
@Morlocci any update?

**Comment by deepak786** [comment]
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/351
