### ISSUE TITLE
Open help center on the Web

### ISSUE THREAD

**Issue by AlehSabadashGmail** [deepak786/intercom_flutter#388]
I am trying to open help center screen on the Web but nothing happen. I only see this message in terminal `Launched the Help Center`

From mobile side it looks like this
<img width="335" alt="Screenshot 2023-12-06 at 16 38 39" src="https://github.com/v3rm0n/intercom_flutter/assets/90776958/16288452-5690-438b-b195-cb13f098e50b">

I tried a few options in intercom client to activate Help Center but seems it did not help me.

The method that I am using is `displayHelpCenter`

**Comment by deepak786** [comment]
As per the [docs](https://developers.intercom.com/installing-intercom/web/methods/#intercomshowspace-spacename), intercom_flutter is doing the same thing.
https://github.com/v3rm0n/intercom_flutter/blob/6cd517bf146b88e49e22b4ebe9588dcdce02e918/intercom_flutter_web/lib/intercom_flutter_web.dart#L220

Can you please test below code:

- Create a file named "test.html".
- Copy and paste the below code in the above created file.
- Add your Intercom APP_ID.
- Open this file in the browser and click the buttons. 
- See if the "help" button is working or not.

```html
<html>

    <script>
        //Set your APP_ID
        var APP_ID = "APP_ID";

        window.intercomSettings = {
            app_id: APP_ID
        };

        (function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',w.intercomSettings);}else{var d=document;var i=function(){i.c(arguments);};i.q=[];i.c=function(args){i.q.push(args);};w.Intercom=i;var l=function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/' + APP_ID;var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);};if(document.readyState==='complete'){l();}else if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();

    </script>

    <body>
        <button type="button" onclick="window.Intercom('showSpace', 'home');">Home</button>
        <button type="button" onclick="window.Intercom('showSpace', 'messages');">Messages</button>
        <button type="button" onclick="window.Intercom('showSpace', 'help');">Help</button>
    </body>

</html>
```

**Comment by AlehSabadashGmail** [comment]
`home` and `messages` work but `help` does not work

**Comment by deepak786** [comment]
Then it must be a bug in Intercom JS SDK. Can you please submit the report to the Intercom support.
**_Note: Don't mention anything about Flutter. You can share the above html sample to reproduce the issue._**

**Comment by deepak786** [comment]
@AlehSabadashGmail I'm checking this issue with the Intercom support.
According to their testing, it is working fine.
See https://d.pr/i/cwQFsu

It seems that something is wrong with your Intercom settings. I need your Intercom app_id so that they can look into it.
Please share your app_id on my email er.deepakgoyal786@gmail.com

**Comment by deepak786** [comment]
Can you add your articles in a collection and see if the help works or not?

**Comment by deepak786** [comment]
@AlehSabadashGmail Any update?

**Comment by AlehSabadashGmail** [comment]
Hey @deepak786 sorry I was on vacation. We decided put web integration off for a few weeks, so I do not have a chance to check it, let's close it for now. I am really appreciate your help, thank you very much for your time

**Comment by Felipe-N0bre** [comment]
Hey guys any update on this? Thanks!
