### ISSUE TITLE
iOS Build failing on version 2.0.5+2

### ISSUE THREAD

**Issue by BasedMusa** [deepak786/intercom_flutter#40]
Getting this after updating to `2.0.5+2`
```
[!] CocoaPods could not find compatible versions for pod "stripe_payment":
  In Podfile:
    stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)

Specs satisfying the `stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Tried running `pod install` and `pod update`. Same error message.

I am on `CocoaPods 1.8.1`

Help would be much appreciated.

**Comment by Zazo032** [comment]
Seems like stripe_payment is using iOS 11 as deployment version: https://github.com/jonasbark/flutter_stripe_payment/blob/0b8270e4601a91dafaf6810dbe96eb8e035ba82e/ios/stripe_payment.podspec#L20

Should we bump it also to that version @v3rm0n ? People using iOS 10 or older probably won't be able to use this plugin, but that's [around 3-5% of iOS users](https://developer.apple.com/support/app-store/).

**Comment by Zazo032** [comment]
The deployment version was upgraded 2 days ago here: 
https://github.com/jonasbark/flutter_stripe_payment/commit/38f1ecbfbcb31d37feba686a3c2f74f3c858bcce#diff-e5cd245bf5ea0b3a286e517f4299937a

**Comment by v3rm0n** [comment]
👍

**Comment by BasedMusa** [comment]
Hey, sorry, I think this might be an issue for the `stripe_payment` plugin. I upgraded that as well, last night.

**Comment by Zazo032** [comment]
Fixed in `stripe_payment`'s latest version ([0.3.1](https://github.com/jonasbark/flutter_stripe_payment/commit/972d4f7415a4b50bc1ca9f9d3473d376b2ef687c)).

**Comment by djanogly** [comment]
Havjng same issue for iOS.

**Comment by NarHakobyan** [comment]
Same issue

**Comment by eyemeroll** [comment]
For iOS, you can try to change your minimum deployment target to ios 10.

**Comment by Zazo032** [comment]
If you're facing similar issues, feel free to open a new issue with more details or try using newer versions of the plugin
