### ISSUE TITLE
The plist file at path `$PATH_TO_APP/ios/Pods/Intercom/Intercom.xcframework/Info.plist` doesn't exist.

### ISSUE THREAD

**Issue by joachimbulow** [deepak786/intercom_flutter#400]
The Intercom library dependency is causing me a severe headache at the moment, and i cannot seem to figure out why I am having issues. 

I am running Flutter version 3.13.1.

When I run `pod install` I get the following error:

```
....
Generating Pods project
`The plist file at path $PATH_TO_APP/ios/Pods/Intercom/Intercom.xcframework/Info.plist `
```

When I remove every reference to `flutter_intercom` I no longer have an issue runnning `pod install`.

I have tried the following:
- Updated MacOS to the latest version (14.3)
- Updated XCode to the latest version (15.2)
- Pruned every cache, restarted system, etc. All the usual suspects for a Flutter build error like this. 

I should probably note, that it works on other users of the same repository, so this issue is mainly if any maintainers have any insights as to what could be the issue.

**Comment by joachimbulow** [comment]
When coworkers are running `pod install` a variety of files are created under `Pods/Intercom/Intercom.xcframework` hereunder:
- Folder called _CodeSignature
- Folder called ios-arm64
- Folder called ios-arm64_x86_64-simuilator
- Info.plist
- LICENSE
- VERSION

Whereas my folder only contains:
- LICENSE

If i try to manually move over the folder to my pods folder, it is replaced with only the `LICENSE` file again, so this is no solution.

**Comment by QoLTech** [comment]
I'm having the same issue.

**Comment by mrehman29** [comment]
Same here

**Comment by deepak786** [comment]
Which `intercom_flutter` version are you using?

**Comment by QoLTech** [comment]
I have tried the last 10 versions on pub.

**Comment by deepak786** [comment]
According to this https://forums.developer.apple.com/forums/thread/689485, there can be 2 possible solutions:

Solution 1:

- In the pod file replace 'use_frameworks!' with 'use_frameworks! :linkage => :static'
- Run 'pod install' // now you might get some other issue
- Revert 'use_frameworks! :linkage => :static' changes i.e replace 'use_frameworks! :linkage => :static' with 'use_frameworks!'
- Again run 'pod install'


Solution 2:

Add `ENV['INFOPLIST_FILE'] = nil` at the top of your pod file


Have you tried any of the above solutions? If not then could you please try?

**Comment by QoLTech** [comment]
I uninstalled cocoapods (brew uninstall cocoapods) and then installed again (brew install cocoapods) and that seems to have worked for me.

I also may have used @deepak786's #1 solution along the way as well, but I don't think that's what did it. I always had :linkage => :static.

I also upgraded from XCode 15.1 to XCode 15.2 (15C500b).

**Comment by simplenotezy** [comment]
@deepak786 We have many dependencies in our project (rather large one) and we only have issues with our intercom dependency.

If we completely remove intercom from our pubspec, we can run `pod install` (and the app in general) without issues.

I suggest we try to investigate why the `flutter_intercom` suddenly causes this issue, while other libraries do not.

What's even more peculiar is that we are 4 developers on the same project and flutter versions, without this issue, but a single one of our devs are facing this. The solution for now is to compress and AirDrop the `Pods` folder over to the broken environment - then `pod install` works fine

**Comment by joachimbulow** [comment]
According to [cocoapods official documentation](https://cocoapods.org/) they _**recommend you use the default ruby**_ for mac.

As mentioned working by @QoLTech i attempted switching over to a brew-installation, which seems to have resolved the issue. 

I see this error being propagated to other Pods, e.g. [here](https://stackoverflow.com/questions/77958227/react-expo-the-plist-file-at-path-doesnt-exist-error-for-specific-pod) related to a React Native project. 

Not sure what is the root cause of this, but keep an eye out @deepak786

**Comment by zigapovhe** [comment]
I've had the same issue. Upgrading cocoapods from 1.15.1 to 1.15.2 fixed it for me.
