### ISSUE TITLE
loginUnidentifiedUser returns error when identity is enforced.

### ISSUE THREAD

**Issue by ayob2k** [deepak786/intercom_flutter#403]
intercom_flutter: ^8.0.11
loginUnidentifiedUser fails when identity is enforced. 
I do:
```
Future  showSupportWidget() async {
    await Intercom.instance.loginUnidentifiedUser();
    await Intercom.instance.displayMessenger();
  }
```
returns:
`E/Intercom: Api call failed: {"type":"error.list","request_id":"0006utgbp2sj52ic20","errors":[{"code":"hmac_mismatch","message":"Failed Identity Verification check"}]}`
![Screenshot 2024-02-08 at 14 09 49](https://github.com/v3rm0n/intercom_flutter/assets/77556307/afc89910-c9a1-4702-afb2-4e5227ad9630)

**Comment by karimafas** [comment]
I am having the exact same issue as above. I have enabled identity verification on our Intercom account, and upon logging in unidentified user and trying to display the messenger, the same error message as above is shown. 

Here is my minimum reproducible example:

```
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Intercom.instance.initialize(
    'my-app-id',
    iosApiKey: 'my-ios-key',
    androidApiKey: 'my-android-key',
  );
  await Intercom.instance.loginUnidentifiedUser();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('Intercom Example'),
        ),
        body: Container(),
        floatingActionButton: FloatingActionButton(
          onPressed: () => Intercom.instance.displayMessenger(),
          tooltip: 'Open Intercom',
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

**Comment by karimafas** [comment]
I have been chatting with Intercom's customer support for the past few days. They deny having introduced fixes for this, but I highly suspect they may have rolled back some changes that introduced a regression for this, as my example above now seems to work without issue. 

@ayob2k could you please check if this has resolved your issue too now?

EDIT: Intercom have actually just notified me they found a bug fix in their commit history for this issue. At least we know where this was coming from!

**Comment by ayob2k** [comment]
@karimafas works now! Thanks alot!

**Comment by karim-cardeo** [comment]
They have actually just found a commit in their history that addresses this bug – at least we know where this was coming from! 🙌
