### ISSUE TITLE
The pod "Intercom" required by the plugin "intercom_flutter" requires a higher minimum iOS deployment version

### ISSUE THREAD

**Issue by sarbogast** [deepak786/intercom_flutter#409]
I just upgraded my project to use intercom_flutter version 8.1.0 and when I build for iOS, I get the following CocoaPods error:

```
Error: The pod "Intercom" required by the plugin "intercom_flutter" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "intercom_flutter", or contact the plugin's developers for assistance.
Error running pod install
Error launching application on iPhone 15 Pro.
```

However the docs still says that it required iOS 13 or higher, and that's what I have in my Podfile and in the iOS project.

`platform :ios, '13.0'`

I tried to upgrade to ios 14.0 instead but it didn't do anything.

**Comment by deepak786** [comment]
@sarbogast In `intercom_flutter: 8.1.0`, Intercom iOS SDK version is updated from 16.5.5 to 16.5.6 and there is no mentioning regarding change in minimum iOS deployment version. See https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md#1656

Not sure why you are getting this error.

/cc @Br1an-Boyle

**Comment by Br1an-Boyle** [comment]
@deepak786 👋🏻 We didn't make any changes to our minimum deployment version in the last while.

**Comment by deepak786** [comment]
@sarbogast starting `intercom_flutter: 9.0.0`, minimum iOS required is 15.
