### ISSUE TITLE
Update User Not Working With New Update

### ISSUE THREAD

**Issue by nihalreddy33** [deepak786/intercom_flutter#41]
I am getting below Exception when trying to call the updateUser. @Zazo032 could you please check if anything got changed in the latest update?

[Intercom] ERROR - Tried to update user but there was a network error (400) - Request failed: bad request (400)
	[C18.1 030FDC65-384D-47A3-B81F-FCDAB86DB0E2 10.20.55.4:51830<->74.125.196.101:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.128s, DNS @0.000s took 0.015s, TCP @0.017s took 0.015s, TLS took 0.051s
	bytes in/out: 4184/1554, packets in/out: 8/10, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 5

**Comment by Zazo032** [comment]
Which platform are you using (Android/iOS)? Which version of the plugin are you using? Which version of Flutter are you using? Physical device or emulator? Could you try to provide a minimum sample app to reproduce the error?

**Comment by nihalreddy33** [comment]
@Zazo032 I am getting this Error on iOS, I am using the latest version 2.0.5+2 and I have tried on both physical & emulator devices. Below is the flutter doctor summary.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.16, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[!] Android Studio (version 2.3)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
[!] IntelliJ IDEA Ultimate Edition (version 2016.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ This install is older than the minimum recommended version of 2017.1.0.
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

**Comment by Zazo032** [comment]
Could you try if this error is still present on latest Flutter's master channel? Could you also try running your app on Android? Did this work before? Per the error message, seems more like a network error

**Comment by Zazo032** [comment]
If this is still an issue, please, file a new issue.
