### ISSUE TITLE
Mention `IntercomAutoIntegratePushNotifications` in iOS setup steps in README

### ISSUE THREAD

**Issue by karimafas** [deepak786/intercom_flutter#411]
Hi folks,

I recently got stuck on an issue that took me some time to resolve. On iOS, when tapping on a push notification that had been received when the app was terminated, the Intercom messenger would display over the app's splash screen as soon as it was launched. 

This can be an issue for apps where security is a concern, since the messenger could potentially open before authentication / PIN entry etc, and display users' personal information shared with support via Intercom.

I eventually resolved this by adding the `IntercomAutoIntegratePushNotifications` param to `Info.plist` and setting its value to `NO` (see [documentation here](https://developers.intercom.com/installing-intercom/ios/push-notifications/#manually))

Would it be worth mentioning this in the package's documentation under the iOS installation steps just in case anybody has a similar issue in future?

**Comment by deepak786** [comment]
@karimafas 
It is already mentioned in the package's documentation to follow the steps from official link.
![Screen Shot 2024-03-02 at 10 07 55 PM](https://github.com/v3rm0n/intercom_flutter/assets/14223997/36adee72-b273-47c8-ba4f-3c90ca14900a)

The embedded link is https://developers.intercom.com/installing-intercom/ios/push-notifications/
