### ISSUE TITLE
Is it possible to customize the size of the messenger window?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [deepak786/intercom_flutter#42]
I looked into the android source code and I didn't see a way to configure the size of the messenger window. It's fine for small devices, but for larger, it's just too big. 
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-10-14 at 14 07 52](https://user-images.githubusercontent.com/23037821/66786443-292f1500-ee95-11e9-9bc3-b8421b99a7ad.png)

**Comment by Zazo032** [comment]
This plugin uses the native tools to render the window, so you should better request that feature to the Intercom team: https://github.com/intercom/intercom-ios

Whenever it is available in the iOS library, you will also be able to use it in Flutter.
