### ISSUE TITLE
How to remove it from memory? I want to close the SDK completely.

### ISSUE THREAD

**Issue by SzymonDziak** [deepak786/intercom_flutter#420]
After Intercom is initialized on web it will never go away. 

To permanently remove the Intercom chat icon from the bottom right of the interface after initialization on the web, a method is required to clear it from memory.

**Comment by deepak786** [comment]
Just remove the dependency, no?

**Comment by SzymonDziak** [comment]
> Just remove the dependency, no?

No, actually we want to keep the dependency and only show the chat on a specific page...

**Comment by deepak786** [comment]
You can use the method [setLauncherVisibility](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/setLauncherVisibility.html)

**Comment by SzymonDziak** [comment]
> You can use the method [setLauncherVisibility](https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom/setLauncherVisibility.html)

Thank you
