### ISSUE TITLE
Does this support listening to unread conversation count?

### ISSUE THREAD

**Issue by JohnMusleh** [deepak786/intercom_flutter#43]
Is there a way to listen to incoming messages/ unread conversation count ?
Suppose you want to listen to the count and update the screen whenever the count changes,

Intercom has this listener for Android:
`Intercom.client().addUnreadConversationCountListener(listener);`

and this for iOS
```
[[NSNotificationCenter defaultCenter] addObserver:self
     selector:@selector(updateUnreadCount:)
         name:IntercomUnreadConversationCountDidChangeNotification
       object:nil];
```

Is this implemented?

**Comment by Zazo032** [comment]
You can see the implemented methods here: https://pub.dev/documentation/intercom_flutter/latest/intercom_flutter/Intercom-class.html

Currently, you can only get the unread conversation count, but not listen to it. That would require an implementation of this new feature in the plugin.

**Comment by JohnMusleh** [comment]
Yes I understand, when do you think this feature would be implemented for this package?

Also while using this package, I get a warning when compiling to Android

> Note: ....\flutter\.pub-cache\hosted\pub.dartlang.org\intercom_flutter-2.0.5+2\android\src\main\jav
> a\io\maido\intercom\PushInterceptService.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.

**Comment by marinat** [comment]
The solution to this issue in the near future?
