### ISSUE TITLE
JS Enabled in a WebView 

### ISSUE THREAD

**Issue by rao21** [deepak786/intercom_flutter#437]
It was observed that the mobile application has enabled JavaScript in WebView. By default, JavaScript is
disabled in WebView, if enabled it can bring various JS-related security issues, such as Cross-Site
Scripting (XSS) attacks.

<img width="1020" alt="Screenshot 2024-06-03 at 20 43 06" src="https://github.com/v3rm0n/intercom_flutter/assets/29813293/05bd6be4-d1ca-4c1a-846a-2aadddd45512">

Any way to set javascript mode disable?

**Comment by deepak786** [comment]
@rao21 From where did you take the code? `intercom_flutter` is not using any webview.

**Comment by rao21** [comment]
> @rao21 From where did you take the code? `intercom_flutter` is not using any webview.

Io\intercom\android\sdk\blocks\Video.java

**Comment by rao21** [comment]
> > @rao21 From where did you take the code? `intercom_flutter` is not using any webview.
> 
> Io\intercom\android\sdk\blocks\Video.java add video enabled javascript here.

**Comment by deepak786** [comment]
Its a native code. intercom_flutter is just a wrapper among the native code.

You can reach out to [Intercom support](https://www.intercom.com/) directly.
