### ISSUE TITLE
issue in integrating with flutter 3.7.0

### ISSUE THREAD

**Issue by TalentKingDev** [deepak786/intercom_flutter#447]
E/flutter (25870): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method loginUnidentifiedUser on channel maido.io/intercom)
E/flutter (25870): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (25870): <asynchronous suspension>
E/flutter (25870): #1      MethodChannelIntercomFlutter.loginUnidentifiedUser (package:intercom_flutter_platform_interface/method_channel_intercom_flutter.dart:83:7)
E/flutter (25870): <asynchronous suspension>
E/flutter (25870):

**Comment by ReeKid2002** [comment]
@TalentKingPython 
Did you get any solution for the above?

**Comment by deepak786** [comment]
Which intercom_flutter version you are using?
Note: loginIdentifiedUser was added in version 7.1.0 (https://pub.dev/packages/intercom_flutter/changelog#710)

**Comment by TalentKingDev** [comment]
I have fixed this issue by using the intercom version upgrade.
Now I am using intercom_flutter v7.5.0
