### ISSUE TITLE
Flutter conflict  build android lib lifecycle-livedata-core-2.8.1-runtime.jar

### ISSUE THREAD

**Issue by gabulcw** [deepak786/intercom_flutter#449]
When I try to build my application using Flutter 3.19.6 I receive this error.

I found a similar issue with React Native https://community.intercom.com/mobile-sdks-24/react-native-android-build-failed-rn-0-72-14-intercom-7-1-3-7398

<img width="680" alt="image" src="https://github.com/user-attachments/assets/9d5e150a-b8fd-44b0-bbd8-b0f0ffcd9386">

**Comment by samnbd** [comment]
Same issue here

**Comment by fan123199** [comment]
I fix this by updating agp version 7.3.0 to 8.3.0. And many related version update also.

**Comment by nikunj-p-7span** [comment]
Same issue here

**Comment by KirioXX** [comment]
Hi, 
I see a similar issue with android builds related to the intercom package.
These are the logs when I run `flutter build apk -v`
[test_app_logs.txt](https://github.com/user-attachments/files/16569733/test_app_logs.txt)

I also setup a test project her:
https://github.com/KirioXX/intercom_test_app
if you run:
```sh
flutter clean && flutter pub get && flutter build apk -v
```
you should see the same result

**Comment by deepak786** [comment]
You need to use AGP version 8. Please follow the below steps:

- android/app/build.gradle
Make sure to add the following under android section
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
```

- android/gradle/wrapper/gradle-wrapper.properties
Update your distributionUrl
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
```

- android/settings.gradle
```
id "com.android.application" version "8.1.4" apply false
id "org.jetbrains.kotlin.android" version "1.9.21" apply false
```

For ref see this commit: https://github.com/v3rm0n/intercom_flutter/commit/6cd517bf146b88e49e22b4ebe9588dcdce02e918

**Comment by samnbd** [comment]
I'm already using gradle 8.5 with Kotlin 1.9.21 using flutter_intercom 9.0.8 and It still crashes the app on release mode. It works fine on debug mode.
I'm using Flutter 3.22.3 btw...

**Comment by deepak786** [comment]
@samnbd 

> It still crashes the app on release mode

Is it not building in release mode using the above steps?

**Comment by deepak786** [comment]
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/436
