### ISSUE TITLE
ANDROID NOT WORKING AT ALL

### ISSUE THREAD

**Issue by SzymonDziak** [deepak786/intercom_flutter#453]
**CONTINOUS PROBLEMS WITH BUILDING FOR ANDROID. ALL YOUR GITHUB TESTS FAILING AS WELL.**

**WHEN CAN WE GET THIS RESOLVED?**

**Comment by KirioXX** [comment]
Hi, 
I see a similar issue with android builds related to the intercom package.
These are the logs when I run `flutter build apk -v`
[test_app_logs.txt](https://github.com/user-attachments/files/16569733/test_app_logs.txt)

I also setup a test project her:
https://github.com/KirioXX/intercom_test_app
if you run:
```sh
flutter clean && flutter pub get && flutter build apk -v
```
you should see the same result

**Comment by deepak786** [comment]
You need to use AGP version 8. Please follow the below steps:

- android/app/build.gradle
Make sure to add the following under android section
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
```

- android/gradle/wrapper/gradle-wrapper.properties
Update your distributionUrl
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
```

- android/settings.gradle
```
id "com.android.application" version "8.1.4" apply false
id "org.jetbrains.kotlin.android" version "1.9.21" apply false
```

**Comment by florinleu** [comment]
@deepak786 I don't think this is a suitable solution since flutter doesn't yet support AGP 8 and we have lots of libraries in our project that are not yet compatible with AGP 8. Is there a way to make it work with AGP 7.6.1, which is the highest version latest recommended by flutter?

**Comment by deepak786** [comment]
Hey @florinleu 

AGP 8 support was added in [intercom_flutter: 8.0.7](https://pub.dev/packages/intercom_flutter/changelog#807)
Try using `intercom_flutter: 8.0.6`

Maybe try using `intercom_flutter: 9.0.4` as per this comment https://github.com/v3rm0n/intercom_flutter/issues/436#issuecomment-2286628777

**Comment by deepak786** [comment]
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/436
