### ISSUE TITLE
I have an issue when building android with flutter using intercom latest version 9.0.9

### ISSUE THREAD

**Issue by AsmaaMagdHelali** [deepak786/intercom_flutter#461]
starting from intercom version 9.0.5. I start to get an error with only in android build only in firebase  packages.
 **Error**: Duplicate class com.google.firebase.Timestamp found in modules jetified-firebase-common-21.0.0-runtime (com.google.firebase:firebase-common:21.0.0) and jetified-firebase-firestore-24.11.0-runtime (com.google.firebase:firebase-firestore:24.11.0)

**Comment by AsmaaMagdHelali** [comment]
???

**Comment by deepak786** [comment]
From the error, seems that the issue is from Firebase packages. 
Could you please try building without the intercom_flutter package to check if you get the same error or not?

If no, then please share the reproducible sample.

**Comment by AsmaaMagdHelali** [comment]
I was able to successfully build the project when I remove the intercom_flutter package

**Comment by AsmaaMagdHelali** [comment]
These are the versions of firebase I used in my project  pub spec file
firebase_core: 2.24.2
firebase_crashlytics: ^3.5.6
cloud_firestore: ^5.3.0

///Android gradel
gradle-7.6-all.zip

 implementation platform('com.google.firebase:firebase-bom:30.4.1')

**Comment by deepak786** [comment]
I'm not sure if it is related but starting `intercom_flutter: 9.0.5` you need to use AGP 8
For more info check this comment https://github.com/v3rm0n/intercom_flutter/issues/436#issuecomment-2286628777

**Comment by minaroid** [comment]
@AsmaaMagdHelali fixed with me after using  intercom_flutter: ^8.1.3

**Comment by AsmaaMagdHelali** [comment]
> @AsmaaMagdHelali fixed with me after using intercom_flutter: ^8.1.3

yes, because starting from intercom_flutter: 9.0.5 they started to use AGP 8 :smiling_face_with_tear: 
so any old version will work perfect in android

**Comment by deepak786** [comment]
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/436
