### ISSUE TITLE
Failed to register or update user. Unauthorized token

### ISSUE THREAD

**Issue by JustineUgo** [deepak786/intercom_flutter#473]
I'm using `intercom_flutter: ^9.1.1`

In main, before the `runApp` function, I initialize the package like this: 
`await Intercom.instance.initialize(<MY App Id>, androidApiKey: <MY Android Key>);`

I've also followed the documentation to create `MyApp.kt` and use it in `AndroidManifest.xml`

Now, when I try to register an identified user and open intercom if fails.

This is how i do it:

```
GestureDetector(
  onTap: () async {
     log("Intercom: Registering user");
    await Intercom.instance.loginIdentifiedUser(email: <User Email> );
    log("Intercom: Done Registering user");
    log("Intercom: Displaying messenger");
    await Intercom.instance.displayMessenger();
    log("Intercom: Done Displaying messenger");
  },
  child: Padding(
    padding: EdgeInsets.only(right: 10.w),
    child: Image.asset(AssetUtil.intercom),
  ),
)
```

But then i get this logs and error

```
[log] Intercom: Registering user
E/Intercom(27622): Failed to register or update user: {"type":"error.list","request_id":"0006pvf0h1igmj0f3vo0","errors":[{"code":"token_unauthorized","message":"Unauthorized token"}]}
[log] Intercom: Done Registering user
[log] Intercom: Displaying messenger
[log] Intercom: Done Displaying messenger

```

Can I get any help around this?

**Comment by deepak786** [comment]
Do you have used the same API key in `MyApp.kt`?

**Comment by JustineUgo** [comment]
Yea @deepak786. I used the same app id and api key on android and flutter intercom initialization methods. I got those information from my intercom account.

**Comment by JustineUgo** [comment]
@deepak786 I had to double check my keys and I found my solution.
I was using an app id and android API key from separate Intercom accounts.

I'll close this issue now.
Thanks for the response, cause it pointed in the right direction.
