### ISSUE TITLE
Issue: issue with receiving notifications when app is in background

### ISSUE THREAD

**Issue by vantoan9708** [deepak786/intercom_flutter#474]
### Hi

Flutter SDK: 3.24.3

### using package: intercom_flutter 9.1.1

**I am using these firebase packages**

  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.1.2
  firebase_messaging_web: ^3.9.1
  firebase_analytics: ^11.3.2
  firebase_database: ^11.1.3
  firebase_dynamic_links: ^6.0.7
  flutter_local_notifications: ^17.0.0

Did I miss any steps to set up notifications on the intercom. If so, please guide me.

### Thank you so much

**Comment by deepak786** [comment]
Have you followed the steps here https://pub.dev/packages/intercom_flutter#push-notifications-setup

**Comment by vantoan9708** [comment]
Our app is setup to **send notifications** from **firebase** and it is working fine. And i am having problem with intercom.

**Comment by vantoan9708** [comment]
Have you checked again. And do you have the same problem as I reported?

Thank you

**Comment by deepak786** [comment]
Are you sending the push notification token to Intercom?

**Comment by vantoan9708** [comment]
I have sent the FCM token code

I use this to send to intercom
Intercom.instance.sendTokenToIntercom(token);

**Comment by vantoan9708** [comment]
I only got the notification here

<img width="300" alt="Screenshot 2024-10-16 at 23 09 03" src="https://github.com/user-attachments/assets/dbfac3c3-6857-4e93-af06-3736ebbfd9c6">

**Comment by deepak786** [comment]
have you setup the FCM on Intercom?
Please follow the steps https://pub.dev/packages/intercom_flutter#push-notifications-setup
https://developers.intercom.com/installing-intercom/android/fcm-push-notifications#step-3.-enable-in-intercom

**Comment by vantoan9708** [comment]
I have it fully setup but. It still doesn't work for me

**Comment by vantoan9708** [comment]
I am getting this message "**Start sending token to Intercom**" it shows I have sent FCM token from intercom_flutter right?

**Comment by vantoan9708** [comment]
I finally fixed it

The problem was that I skipped this setup step. I think this will help everyone.
<img width="1431" alt="Screenshot 2024-10-17 at 18 12 47" src="https://github.com/user-attachments/assets/7896bb4b-dce5-47cf-a6e7-1a67ecf1e5a8">


Thank you.

**Comment by vantoan9708** [comment]
Are you having the crash issue like I reported here?
https://github.com/v3rm0n/intercom_flutter/issues/475
