### ISSUE TITLE
IntercomFlutterPlugin

### ISSUE THREAD

**Issue by ashish-live** [deepak786/intercom_flutter#477]
Any specific reason why do we need to initialize it from MainActivity.kt in Android as we are already initializing this in our main.dart?

`IntercomFlutterPlugin.initSdk(this, appId = "appId", androidApiKey = "androidApiKey")`

**Comment by deepak786** [comment]
According to the documentation, Intercom must be initialized in the Application onCreate.
Otherwise it throws the following error:

```
Caused by io.intercom.android.sdk.exceptions.IntercomIntegrationException
Intercom was not initialized correctly, Intercom.initialize() needs to be called in onCreate() in your Application class.
```
