### ISSUE TITLE
How to wrap intercom page?

### ISSUE THREAD

**Issue by fauzipadlaw** [deepak786/intercom_flutter#48]
How to wrap intercom page in flutter widget?

**Comment by BasedMusa** [comment]
You can't, the `displayMessenger()` function calls native code. Not Flutter.

**Comment by Zazo032** [comment]
As @BasedMusa, you can't do that since this plugin directly calls each platform's native code.

**Comment by fauzipadlaw** [comment]
got it, thanks for the answer
