### ISSUE TITLE
Chat never loading on Intercom_flutter 9.2.0 and Flutter 3.24.5

### ISSUE THREAD

**Issue by SzymonDziak** [deepak786/intercom_flutter#485]
Stuck on this screen... no errors.  tested iOS. web works fine. 

![simulator_screenshot_A5125C0F-D485-49B1-A6E8-A3014CD3B909](https://github.com/user-attachments/assets/e9d579b2-29c5-4354-a104-14d84295c779)

**Comment by deepak786** [comment]
Not sure what could be the reason. Maybe an issue with Intercom initialization or an issue in native SDK.

**Comment by SzymonDziak** [comment]
Are you able to replicate on your end?

> Not sure what could be the reason. Maybe an issue with Intercom initialization or an issue in native SDK.
