### ISSUE TITLE
Intercom messages got cut off in the chat

### ISSUE THREAD

**Issue by kean-fetchpet** [deepak786/intercom_flutter#486]
Hi, 

Lately a few of our customers been noticing in-app messages from intercom got cut off. See the message below. So it should be "We are sorry to hear about that! Poor boy, must have been very stressful." but in-app messages were "We are sorry to hear about that! Poor boy, must have been very". How can i fix the issue? Any help is appreciated. 🙏 

Platform: iPhone 15 (ios 17.6.1) 
Flutter version:  3.24.3 
Intercom package: 8.1.0

<img width="400" alt="Screenshot 2024-11-22 at 12 36 17 PM" src="https://github.com/user-attachments/assets/05c83417-2d60-4449-a516-039e36251d3a">

**Comment by deepak786** [comment]
You are using the old version of intercom_flutter. Latest version is `intercom_flutter: 9.2.0`.
Maybe the issue is already fixed in-between. So try the updated version.

**Comment by deepak786** [comment]
Seems that the issue was fixed in Intercom iOS version [17.0.0](https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md#1700)
`intercom_flutter: 9.0.0` is using the Intercom iOS version 17.0.0

**Comment by kean-fetchpet** [comment]
@deepak786 thank you so much 🙏
