### ISSUE TITLE
In-App Notification Stuck To Bottom Of Screen (Android)

### ISSUE THREAD

**Issue by dkobia** [deepak786/intercom_flutter#493]
When I create an outbound post/chat in Intercom, when it pops up for the user, the in-app notice/notification at the bottom of the screen cannot be removed. It cannot be swiped or tapped on Android and the only way to remove it is to open Intercom, go to messages and tap the specific message which clears it as read. As you can imagine it is a major annoyance for users and only happens on Android.

**Comment by deepak786** [comment]
@dkobia What is your MainActivity in Android extending from? FlutterActivity? or FlutterFragmentActivity?
Make sure to extend it from FlutterFragmentActivity.
See documentation https://pub.dev/packages/intercom_flutter#android and related issue https://github.com/v3rm0n/intercom_flutter/issues/351

**Comment by dkobia** [comment]
Thank you @deepak786, using `FlutterFragmentActivity` over `FlutterActivity` is indeed the solution.
