### ISSUE TITLE
[Android] Invalid cast from `FlutterPluginRegistrar` to `android.app.Application`

### ISSUE THREAD

**Issue by nstosic-toptal** [deepak786/intercom_flutter#57]
In `IntercomFlutterPlugin.kt` the library tries to cast the instance of `FlutterPluginRegistrar` to `(android.app.)Application` type. However, newer Flutter SDKs have changed the Android implementation to prefer `Activity` as the instance of `FlutterPluginRegistrar`.

This is the line that's causing the issue:

https://github.com/v3rm0n/intercom_flutter/blob/master/android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt#L22

A working hotfix would be to change that line to:
```
channel.setMethodCallHandler(IntercomFlutterPlugin(registrar.context().applicationContext as Application))
```

**Comment by Zazo032** [comment]
Is this a warning or an error right now? I think this might be solved when #55 is addressed. As a workaround, your proposed change might work. Would you like to fill a PR fixing it?

**Comment by nstosic-toptal** [comment]
Whoa! That's an incredibly quick response.

I also think #55 would fix this. As for the PR, I literally had my first encounter with this library yesterday, so I'm not sure I'm the right person because of potential regressions or author's API design philosophy.

**Comment by Zazo032** [comment]
I can have a look at migrating to V2 embedding when I have some free time, but I'm currently too busy to work on it

**Comment by nstosic-toptal** [comment]
Is there any progress with this request?
