### ISSUE TITLE
Why is min SDK 21? 

### ISSUE THREAD

**Issue by KingIdee** [deepak786/intercom_flutter#62]
Please, I'll like to know why the minimum SDK was moved to 21. My own min SDK is at 16 and I have a couple of customers on that version. I'll like to know if there's a change that really warranted this.

**Comment by Spikes042** [comment]
#53

**Comment by Zazo032** [comment]
As @Spikes042 said, Intercom raised the minimum required version to the ones this plugin requires now. You can find more info on the attached issue.
