### ISSUE TITLE
CocoaPods could not find compatible versions for pod "intercom_flutter":

### ISSUE THREAD

**Issue by AdamBCo** [deepak786/intercom_flutter#64]
I keep getting the following error when attempting to build on iOS using version ^2.1.1 of intercom_flutter.

    CocoaPods could not find compatible versions for pod "intercom_flutter": In Podfile: intercom_flutter (from `.symlinks/plugins/intercom_flutter/ios`)

    Specs satisfying the `intercom_flutter (from `.symlinks/plugins/intercom_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

Has anyone run into this issue before? How do you resolve it?

**Comment by Spikes042** [comment]
The plugin now requires iOS 10 minimum. You need to up your minimum supported version
#53

**Comment by Zazo032** [comment]
Thanks @Spikes042!
@AdamBCo previous answer sums up the issue with a solution
