### ISSUE TITLE
AndroidManifest.xml merge error with Flutter apps with minSdk less than version 21.

### ISSUE THREAD

**Issue by Lekky71** [deepak786/intercom_flutter#68]
`The prefix "tools" for attribute "tools:overrideLibrary" associated with an element type "uses-sdk" is not bound.`

**Comment by deepak786** [comment]
@Lekky71 Intercom Supports only `Android API >=21` and `iOS version >=10`.
If you want to support intercom on the API version lower than 21 in Android, you need to override the library.

```
<!-- Intercom SDK supports min SDK 21 -->
    <uses-sdk tools:overrideLibrary="io.maido.intercom, io.intercom.android, io.intercom.android.sdk.fcm, io.intercom.android.sdk, com.intercom.input.gallery, com.intercom.composer" />
```
And you need to handle the lower API version in your app itself so that it will not crash.

**Comment by deepak786** [comment]
for the iOS version < 10, the app will not compile with intercom_flutter because intercom requires iOS version >= 10.
