### ISSUE TITLE
Register Identified User by email

### ISSUE THREAD

**Issue by joaocarloscabral** [deepak786/intercom_flutter#7]
Hello,
Would be possible to include email as a way to register identified user?

**Comment by GeertJohan** [comment]
It can be done, at least for Android.. https://developers.intercom.com/installing-intercom/docs/android-installation
But it will require work in this plugin to expose the feature in Dart.

What I've done is, I've set the `user_id` on users to be equal to `email`. This is being done by a bit of server-side software using the Intercom API. Email address can now be used as user_id identifier from the app.

Note that there's also a field `id` on users, which is not the same as `user_id`.
`id` is generated by Intercom, but `user_id` can be changed by you using the Intercom API.

**Comment by v3rm0n** [comment]
Added email to `registerIdentifiedUser` released as 2.0.0 since the API changed
