### ISSUE TITLE
 java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by bakua** [deepak786/intercom_flutter#72]
Hello,

I am running into the following issue. Hope that helps.

```
      call.method == "setInAppMessagesVisibility" -> {
        val visibility = call.argument<String>("visibility")
        if(visibility != null) {
          Intercom.client().setInAppMessageVisibility(Intercom.Visibility.valueOf(visibility))
          result.success("Showing in app messages: $visibility")
        }
        result.success("Launched")
      }
```

Calling result.success twice on one result instance is not allowed for plugins.

**Comment by marinat** [comment]
I have same issue

**Comment by Isakdl** [comment]
Same issue, can we have this fix merged?

**Comment by Zazo032** [comment]
Seems to be an issue with Flutter: https://github.com/flutter/flutter/issues/29092

**Comment by bakua** [comment]
> Seems to be an issue with Flutter: [flutter/flutter#29092](https://github.com/flutter/flutter/issues/29092)

It is incorrect to call reply.success multiple times on one reply instance at the moment. The code snipped above can be easily fixed to behave correctly.

**Comment by Zazo032** [comment]
Seems like @Luk3s [fixed it](https://github.com/usetouco/intercom_flutter/commit/7e7cc23b84f984faebdbd9e369b6737b8c67f11a), would you mind opening a PR with that change?
@bakua does that commit solve it?

**Comment by eimantas1998** [comment]
Hello, did this issue got solved?

**Comment by Zazo032** [comment]
Seems to be solved. If this is still an issue, please file a new one.
