### ISSUE TITLE
Intercom Push + firebase_messaging

### ISSUE THREAD

**Issue by mrangelba** [deepak786/intercom_flutter#73]
Hello,

I followed the steps of setting up the intercom with firebase messaging.

When receiving a message directly from firebase, the message is not displayed or forwarded to firebase messaging. The "Push message received, not for Intercom" log is displayed.

**Comment by gabdsg** [comment]
I have the same problem

**Comment by mrangelba** [comment]
@gabdsg

I created the intercept of the android project, to forward the messages to the intercom or firebase.

```java
package com.example.intercom;

import com.google.firebase.messaging.RemoteMessage;`
import com.google.firebase.messaging.FirebaseMessagingService;
import io.intercom.android.sdk.push.IntercomPushClient;
import android.content.Intent;
import android.util.Log;
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
import java.util.Map;

public class FAPushInterceptService extends FirebaseMessagingService {
    private static final String TAG = "PushInterceptService";
    private static final String ACTION_REMOTE_MESSAGE =
            "io.flutter.plugins.firebasemessaging.NOTIFICATION";
    private static final String EXTRA_REMOTE_MESSAGE = "notification";
    private final IntercomPushClient intercomPushClient = new IntercomPushClient();

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        Map message = remoteMessage.getData();

        if (intercomPushClient.isIntercomPush(message)) {
            Log.d(TAG, "Intercom message received");
            intercomPushClient.handlePush(getApplication(), message);
        } else {
            Log.d(TAG, "Push message received, not for Intercom");
            Intent intent = new Intent(ACTION_REMOTE_MESSAGE);
            intent.putExtra(EXTRA_REMOTE_MESSAGE, remoteMessage);
            LocalBroadcastManager.getInstance(this).sendBroadcast(intent);
        }
    }
}
```

Add on AndroidManifest.xml

```xml
        <service android:name=".FAPushInterceptService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Add on app/build.gradle

```gradle
    implementation 'io.intercom.android:intercom-sdk:6.0.1'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
```

**Comment by gabdsg** [comment]
@mrangelba  I have this problem on iOS.

**Comment by aram-uruworks** [comment]
+1

**Comment by kasyrm** [comment]
I have similar problem. I turned off the intercom swizzling because it made configure method from FirebaseMessaging to stop receiving call backs. Now I can receive and react to all my other pushes but intercom pushes do not trigger the configure onResume and onLaunch callbacks.

**Comment by swidnikk** [comment]
Any recommendation or workaround for this issue? I'd like to be able to send/schedule push notifications from Intercom and in some situations also send via firebase

**Comment by acoutts** [comment]
> @gabdsg
> 
> I created the intercept of the android project, to forward the messages to the intercom or firebase.
> 
> ```java
> package com.example.intercom;
> 
> import com.google.firebase.messaging.RemoteMessage;`
> import com.google.firebase.messaging.FirebaseMessagingService;
> import io.intercom.android.sdk.push.IntercomPushClient;
> import android.content.Intent;
> import android.util.Log;
> import androidx.localbroadcastmanager.content.LocalBroadcastManager;
> import java.util.Map;
> 
> public class FAPushInterceptService extends FirebaseMessagingService {
>     private static final String TAG = "PushInterceptService";
>     private static final String ACTION_REMOTE_MESSAGE =
>             "io.flutter.plugins.firebasemessaging.NOTIFICATION";
>     private static final String EXTRA_REMOTE_MESSAGE = "notification";
>     private final IntercomPushClient intercomPushClient = new IntercomPushClient();
> 
>     @Override
>     public void onMessageReceived(RemoteMessage remoteMessage) {
>         super.onMessageReceived(remoteMessage);
> 
>         Map message = remoteMessage.getData();
> 
>         if (intercomPushClient.isIntercomPush(message)) {
>             Log.d(TAG, "Intercom message received");
>             intercomPushClient.handlePush(getApplication(), message);
>         } else {
>             Log.d(TAG, "Push message received, not for Intercom");
>             Intent intent = new Intent(ACTION_REMOTE_MESSAGE);
>             intent.putExtra(EXTRA_REMOTE_MESSAGE, remoteMessage);
>             LocalBroadcastManager.getInstance(this).sendBroadcast(intent);
>         }
>     }
> }
> ```
> 
> Add on AndroidManifest.xml
> 
> ```
>         <service android:name=".FAPushInterceptService">
>             <intent-filter>
>                 <action android:name="com.google.firebase.MESSAGING_EVENT" />
>             </intent-filter>
>         </service>
> ```
> 
> Add on app/build.gradle
> 
> ```groovy-gradle
>     implementation 'io.intercom.android:intercom-sdk:6.0.1'
>     implementation 'com.google.firebase:firebase-messaging:20.0.1'
> ```

This worked for me too- thanks! One thing I had to also do was call `await Intercom.handlePushMessage();` when the app is resumed to handle someone tapping the notification to launch the app.

This should probably be submitted as PR to the lib as the push interceptor included just hijacks all pushes and never forwards anything on.

**Comment by deepak786** [comment]
could you please test the updated/latest intercom_flutter:

```
intercom_flutter: 4.0.0
```

Follow this thread #149 for how to use the method `sendTokenToIntercom`

But you need to handle the notification callback (background + foreground) from firebase_messaging with the below code:

```
if (await Intercom.isIntercomPush(data)) {
    // notification will be handled by the Intercom
    await Intercom.handlePush(data);
    return;
}

// else handle the notification 
```

_Note: method Intercom.isIntercomPush is not implemented for iOS. so you need to take care of that also either use Platform check or wrap your code in a try-catch block._
