### ISSUE TITLE
Push notification and handeling onBackgroundMessage

### ISSUE THREAD

**Issue by Isakdl** [deepak786/intercom_flutter#78]
I'm running firebase_messaging with background push notifications. I'm trying to configure this plugin to work with that setup. 

So far I got normal intercom push notifications to work with this in the AndroidManifest
```
        <service
            android:name="io.maido.intercom.PushInterceptService"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Now with that firebase messaging does not pick up the push notification. Fair enough the documentation even says this.

But when I remove the config in the AndroidManifest and configure my onBackgroundMessage like so:
```
static Future<dynamic> _onBackgroundMessage(Map<String, dynamic> message) async {

    if (message.containsKey("data")) {
      final data = (message['data'] as Map).cast<String, dynamic>();

      if (await Intercom.isIntercomPush(data)) {
        await Intercom.handlePush(data);
        return;
      }
    }

    // Here you can handle your own background messages
  }
```

I get this error if the app is in the background, It does however work as expected when the app is in the foreground.
```
I/flutter (15234): Unable to handle incoming background message.
I/flutter (15234): MissingPluginException(No implementation found for method isIntercomPush on channel maido.io/intercom)
```

Is this related to how plugins are registered? Does this plugin support the new plugin registering api? 

I did reconfigure my app after flutter 1.12.x for the new FlutterEngine system.

**Comment by Spikes042** [comment]
What platform and versions are you running.
Include Intercom, firebase_messaging and flutter versions please

**Comment by Isakdl** [comment]
Flutter: 1.17.3 and 1.17.2 (tried both)

```
intercom_flutter: ^2.2.0
firebase_messaging: ^6.0.16
```

**Comment by Isakdl** [comment]
I have done some more research and it does indeed seem like the problem is how the plugin is embedded, I think this plugin uses the Plugin Embedding v1 I.E. the older pre 1.12 way to embed a plugin. This means that it will not work in a flutter app that is configured for the embedding v2 without doing a manual registering of the plugin. 

Found this explanation:
https://stackoverflow.com/questions/59611258/in-flutter-how-do-we-use-firebase-messaging-onbackgroundmessage-to-create-a-not

And this plugin explaining how they have it setup: https://pub.dev/packages/android_alarm_manager#flutter-android-embedding-v1

So to get background notifications to work for newer/migrated Flutter projects this package would have to be  migrated to the emedding v2 or the very least supply a callback function to registering the plugin manually.

**Comment by Isakdl** [comment]
Solved it!!

So for people with migrated projects you have to manually register the plugin!

I use java but same applies to kotlin

go to android/app/src/main/java/path/to/app/Application.java

and add this line `IntercomFlutterPlugin.registerWith(registry.registrarFor("io.maido.intercom.IntercomFlutterPlugin"));` to the registerWith function!

Like so:
```
package path.to.app;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.maido.intercom.IntercomFlutterPlugin;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    IntercomFlutterPlugin.registerWith(registry.registrarFor("io.maido.intercom.IntercomFlutterPlugin"));
  }
}
```

For kotlin use kotlin syntax!

**Comment by Isakdl** [comment]
I might have jumped the gun a bit to quick here...

My application.java actually looks like this:

```
package path.to.app;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;
import io.maido.intercom.IntercomFlutterPlugin;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    IntercomFlutterPlugin.registerWith(registry.registrarFor("io.maido.intercom.IntercomFlutterPlugin"));
    FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
  }
}
```

it seems it did work because I'm also registering the firebase messaging plugin in Application.java and if I place the intercom plugin regsiterWith above the firebase one, the intercom plugin works in the background, but the app will throw an error for firebase

```
Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)
```

and if we swap places of the two registerWith funtions we get another error

```
Unhandled Exception: PlatformException(error, path.to.app.MainActivity cannot be cast to android.app.Application, null)
```

Everything seems to work like it should if we register the intercomplugin first, we just get ugly error prints on startup.. Not sure what has to be done to fix this. Probably a propper embedded v2 implementation.

**Comment by deepak786** [comment]
could you please test the updated/latest intercom_flutter

```
intercom_flutter: 4.0.0
```

Follow this thread #149 for how to use the method `sendTokenToIntercom`

But you need to handle the notification callback (background + foreground) from `firebase_messaging` with the below code:
```
if (await Intercom.isIntercomPush(data)) {
    await Intercom.handlePush(data);
    return;
}
```

_Note: method `Intercom.isIntercomPush` is not implemented for iOS. so you need to take care of that also either use Platform check or wrap your code in a try-catch block._

**Comment by geoox** [comment]
@deepak786 Do you have any idea how can one handle the iOS notifications more specifically? For example, I need to store all the notifications received in a separate view and need a function similar to 'onBackgroundHandler' from Firebase Messaging.

**Comment by deepak786** [comment]
@geoox for the iOS notifications, Intercom uses APNS. you can try this https://developers.intercom.com/installing-intercom/docs/ios-push-notifications#step-4-handling-intercom-push-notifications to manually handle the push notifications.
