### ISSUE TITLE
(No implementation found for method initialize on channel maido.io/intercom

### ISSUE THREAD

**Issue by geekhenno** [deepak786/intercom_flutter#80]
I get this error, anyone know why?

(No implementation found for method initialize on channel maido.io/intercom

**Comment by Isakdl** [comment]
See my issue: https://github.com/v3rm0n/intercom_flutter/issues/78 the problem seems to be that you are using the new plugin interface in your flutter app but this package is not migrated to support it currently.

**Comment by Isakdl** [comment]
I actually solved it for my project!


go to android/app/src/main/java/path/to/app/Application.java
and add this line `IntercomFlutterPlugin.registerWith(registry.registrarFor("io.maido.intercom.IntercomFlutterPlugin"));` to the registerWith function!

See https://github.com/v3rm0n/intercom_flutter/issues/78 for more details.

**Comment by ghost** [comment]
where exactly to put this line? because my app doesnt have Application.java

**Comment by mwawrusch** [comment]
Just ran into this as well.

**Comment by ghost** [comment]
#78 does not solve this for me.

Please provide a propper update for the v2 embedding.

**Comment by deepak786** [comment]
The Flutter V2 was embedded already.
try the intercom_flutter: 5.0.0 latest version.
