### ISSUE TITLE
Upgrade to version 7 of intercom SDK

### ISSUE THREAD

**Issue by m4rcelofs** [deepak786/intercom_flutter#81]
Similar to https://github.com/v3rm0n/intercom_flutter/issues/53, but this time Intercom is not (yet) deprecating the SDK v6.

There doesn't seem to be any breaking changes on Android (still API 21+).

iOS requires 10+, and there's a [whole page about migrating to v7](https://developers.intercom.com/installing-intercom/docs/migrating-to-v710), but it seems to be more of a "getting out of iOS 8 & 9" thing which would also apply when migrating from SDK v5 to SDK v6. Not sure about this one though.

**Comment by duniapay** [comment]
Hi, The "mobile caroussel" feature is only available in the version 7.
