### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method sendTokenToIntercom on channel maido.io/intercom)

### ISSUE THREAD

**Issue by TechnoPrashant** [deepak786/intercom_flutter#84]
When i run app in ios

**Comment by Spikes042** [comment]
duplicate of #29

**Comment by HananKamal-VG** [comment]
@Zazo032  When will the new version publish and be available for use ?

**Comment by Zazo032** [comment]
> @Zazo032 When will the new version publish and be available for use ?

Hi, it should be available now as `2.2.1` on pub.dev
