### ISSUE TITLE
Missing web implementation

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [deepak786/intercom_flutter#86]
As Flutter web is now seeing major adoption and has already been in the **beta** stage for quite some time, Flutter web support is a good idea.

Anyways, this plugin is currently missing web support and that would be great to have 😃

**Comment by duttaoindril** [comment]
Hi, I'd like to second this and maybe even contribute, how do I get started?

**Comment by creativecreatorormaybenot** [comment]
@duttaoindril I would say that https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6 is what you want to look at to get started :)

cc @Zazo032 @v3rm0n

**Comment by deepak786** [comment]
https://github.com/v3rm0n/intercom_flutter/pull/111

**Comment by deepak786** [comment]
`intercom_flutter: 5.0.0` is released with web support.
Don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid :)
