### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "stripe_payment":   In Podfile:     stripe_payment

### ISSUE THREAD

**Issue by sumitrvi** [deepak786/intercom_flutter#87]
Hi've getting pod file issue when i'm using stripe_payment package

**Comment by marinat** [comment]
It's intercom library, dude.

**Comment by theweiweiway** [comment]
LOL

**Comment by aqarchy** [comment]
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
platform :ios, '11.0'
