### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by eimantas1998** [deepak786/intercom_flutter#90]
Hello, still experencing this issue in the newest version of the package.

Stacktrace:
E/MethodChannel#maido.io/intercom(16283): Failed to handle method call
E/MethodChannel#maido.io/intercom(16283): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#maido.io/intercom(16283):       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/MethodChannel#maido.io/intercom(16283):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:235)
E/MethodChannel#maido.io/intercom(16283):       at io.maido.intercom.IntercomFlutterPlugin.onMethodCall(IntercomFlutterPlugin.kt:99)
E/MethodChannel#maido.io/intercom(16283):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#maido.io/intercom(16283):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#maido.io/intercom(16283):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#maido.io/intercom(16283):       at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#maido.io/intercom(16283):       at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#maido.io/intercom(16283):       at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#maido.io/intercom(16283):       at android.app.ActivityThread.main(ActivityThread.java:6523)
E/MethodChannel#maido.io/intercom(16283):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#maido.io/intercom(16283):       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#maido.io/intercom(16283):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/DartMessenger(16283): Uncaught exception in binary message listener
E/DartMessenger(16283): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(16283):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/DartMessenger(16283):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:250)
E/DartMessenger(16283):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(16283):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/DartMessenger(16283):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(16283):         at android.os.MessageQueue.next(MessageQueue.java:356)
E/DartMessenger(16283):         at android.os.Looper.loop(Looper.java:138)
E/DartMessenger(16283):         at android.app.ActivityThread.main(ActivityThread.java:6523)
E/DartMessenger(16283):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(16283):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/DartMessenger(16283):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Related issue:
https://github.com/v3rm0n/intercom_flutter/issues/72

**Comment by algirdasmac** [comment]
Seems that the fix is possible with this:
https://github.com/usetouco/intercom_flutter/commit/7e7cc23b84f984faebdbd9e369b6737b8c67f11a

Could we get this merged in main package?

**Comment by Zazo032** [comment]
@usetouco @Luk3s feel free to send a PR with your changes so this can be fixed too upstream
